<?php
	
	if (! $nav_bg)
		$nav_bg = "#000000";
	if (! $nav_gradient_top)
		$nav_gradient_top = "#000000";
	if (! $nav_gradient_bottom)
		$nav_gradient_bottom = "#000000";
	if (! $nav_active_gradient_top)
		$nav_active_gradient_top = "#333333";
	if (! $nav_active_gradient_bottom)
		$nav_active_gradient_bottom = "#111111";
	if (! $nav_bd)
		$nav_bd = "#111111";
	if (! $nav_icon_colour)
		$nav_icon_colour = "#999999";
	if (! $nav_active_icon_colour)
		$nav_active_icon_colour = "#ffffff";
	if (! $link_colour)
		$link_colour = "#ffffff";
	if (! $banner_colour)
		$banner_colour = "#999999";
	if (! $search_background)
		$search_background = "#999999";
	if (! $bgcolour)
		$bgcolour = "#111111";
	if (! $item_colour)
		$item_colour = "#111111";
	if (! $toolicon_colour)
		$toolicon_colour = '#999999';
	if (! $toolicon_activecolour)
		$toolicon_activecolour = '#ffffff';
	if (! $font_colour)
		$font_colour = "#cccccc";
