<?php
	
	if (! $nav_bg)
		$nav_bg = "#000";
	if (! $nav_gradient_top)
		$nav_gradient_top = "#000";
	if (! $nav_gradient_bottom)
		$nav_gradient_bottom = "#000";
	if (! $nav_active_gradient_top)
		$nav_active_gradient_top = "#000";
	if (! $nav_active_gradient_bottom)
		$nav_active_gradient_bottom = "#000";
	if (! $nav_bd)
		$nav_bd = "#000";
	if (! $nav_icon_colour)
		$nav_icon_colour = "#32962D";
	if (! $nav_active_icon_colour)
		$nav_active_icon_colour = "#50f148";
	if (! $navmenu_bgchover)
		$navmenu_bgchover = "#143D12";
	if (! $navmenu_bgimage)
		$navmenu_bgimage = "background-image: none;";
	if (! $navtabs_borderc)
		$navtabs_borderc = "#143D12";
	if (! $navtabs_fontcolour)
		$navtabs_fontcolour = "#46D43F";
	if (! $navtabs_bgcolour)
		$navtabs_bgcolour = "#000";
	if (! $navtabs_linkcolour)
		$navtabs_linkcolour = "color: #50f148;";
	if (! $navtabs_linkchover)
		$navtabs_linkchover = "color: #50f148;";
	if (! $navtabs_bgchover)
		$navtabs_bgchover = "#000";
	if (! $navtabs_decohover)
		$navtabs_decohover = "underline";
if (! $navaside_bghover)
		$navaside_bghover = "#143D12";
	if (! $link_colour)
		$link_colour = "#50f148";
	if (! $link_font_weight)
		$link_font_weight = "bold";
	if (! $selected_active_colour)
		$selected_active_colour = "#50f148";
	if (! $selected_active_deco)
		$selected_active_deco = "underline";
	if (! $banner_colour)
		$banner_colour = "#000";
	if (! $search_background)
		$search_background = "#000";
	if (! $bgcolour)
		$bgcolour = "#000";
	if (! $genericcontent_bgcolour)
		$genericcontent_bgcolour = 'rgba(0,0,0,0.8)';
	if (! $item_colour)
		$item_colour = "rgba(0,0,0,0.8)";
	if (! $comment_item_colour)
		$comment_item_colour = "rgba(0,0,0,0.4)";
	if (! $comment_border_colour)
		$comment_border_colour = "rgba(0,0,0,0.8)";
	if (! $toolicon_colour)
		$toolicon_colour = '#32962D';
	if (! $toolicon_activecolour)
		$toolicon_activecolour = '#50f148';
	if (! $font_colour)
		$font_colour = "#46D43F";
	if (! $blockquote_colour)
		$blockquote_colour = "#32962D";
	if (! $blockquote_bgcolour)
		$blockquote_bgcolour = "#000";
	if (! $blockquote_bordercolour)
		$blockquote_bordercolour = "#143D12";
	if (! $code_borderc)
		$code_borderc = "#143D12";
	if (! $code_bgcolour)
		$code_bgcolour = "#000";
	if (! $code_txtcolour)
		$code_txtcolour = "#32962D";
	if (! $pre_borderc)
		$pre_borderc = "#143D12";
	if (! $pre_bgcolour)
		$pre_bgcolour = "#000";
	if (! $pre_txtcolour)
		$pre_txtcolour = "#32962D";
	if (! $item_bordercolour)
		$item_bordercolour = "#143D12";
	if (! $notif_itemcolour)
		$notif_itemcolour = "#50f148";
	if (! $notif_itemhovercolour)
		$notif_itemhovercolour = "#50f148";
	if (! $acpopup_bgcolour)
		$acpopup_bgcolour = "#000";
	if (! $acpopup_bordercolour)
		$acpopup_bordercolour = "#143D12";
	if (! $acpopup_tgbl_bgcolour)
		$acpopup_tgbl_bgcolour = "#000";
	if (! $acpopup_hovercolour)
		$acpopup_hovercolour = "#50f148";
	if (! $editbuttons_bgcolour)
		$editbuttons_bgcolour = "#000";
	if (! $editbuttons_bordercolour)
		$editbuttons_bordercolour = "#143D12";
	if (! $editbuttons_colour)
		$editbuttons_colour = "#32962D";
	if (! $editbuttons_bghover)
		$editbuttons_bghover = "#000";
	if (! $dropdown_bgcolour)
		$dropdown_bgcolour = "#000";
	if (! $dropdown_textcolour)
		$dropdown_textcolour = "#32962D";
	if (! $dropdown_txtcolhover)
		$dropdown_txtcolhover = "#50f148";
	if (! $dropdown_bgcolhover)
		$dropdown_bgcolhover = "#143D12";
	if (! $dropdown_bgimghover)
		$dropdown_bgimghover = "background-image: none;";
	if (! $dropdown_togglecol)
		$dropdown_togglecol = "#50f148";
	if (! $dropdown_togglebgcol)
		$dropdown_togglebgcol = "#000";
	if (! $dropdown_bordercol)
		$dropdown_bordercol = "#143D12";
	if (! $preview_backgroundimg)
		$preview_backgroundimg = "gray_and_black_diagonal_stripes_background_seamless.gif";
	if (! $notify_bgcolour)
		$notify_bgcolour = "#000";
	if (! $notify_linkcolour)
		$notify_linkcolour = "#50f148";	
	if (! $notify_bghover)
		$notify_bghover = "#000";
	if (! $notify_topmargin)
		$notify_topmargin = "-1px";
	if (! $notifyseen_bgcolour)
		$notifyseen_bgcolour = "#000";
	if (! $notifyseen_linkcolour)
		$notifyseen_linkcolour = "#000";
	if (! $notifyseen_bghover)
		$notifyseen_bghover = "#000";
	if (! $notifyseen_linkhover)
		$notifyseen_linkhover = "#50f148";
	if (! $input_bgsubmit)
		$input_bgsubmit = "#000";
	if (! $input_linksubmit)
		$input_linksubmit = "#50f148";
	if (! $input_border)
		$input_border = "#143D12";
	if (! $input_colourhover)
		$input_colourhover = "#50f148";
	if (! $input_decohover)
		$input_decohover = "underline";
	if (! $acl_bgcolour)
		$acl_bgcolour = "#000";
	if (! $acl_bordercolour)
		$acl_bordercolour = "#000";
	if (! $aclbutton_linkcolour)
		$aclbutton_linkcolour = "color: #fff;";
	if (! $abookself_bgcolour)
		$abookself_bgcolour = "#000";
	if(! $infomess_bgcolour)
		$infomess_bgcolour = "#000";
