<XML>
  <post>
    <like>
      <positive>{{$positive}}</positive>
      <guid>{{$guid}}</guid>
      <target_type>{{$target_type}}</target_type>
      <parent_guid>{{$parent_guid}}</parent_guid>
      <author_signature>{{$authorsig}}</author_signature>
      <diaspora_handle>{{$handle}}</diaspora_handle>
    </like>
  </post>
</XML>
