<XML>
  <post>
    <reshare>
      <root_diaspora_id>{{$root_handle}}</root_diaspora_id>
      <root_guid>{{$root_guid}}</root_guid>
      <guid>{{$guid}}</guid>
      <diaspora_handle>{{$handle}}</diaspora_handle>
      <public>{{$public}}</public>
      <created_at>{{$created}}</created_at>
      <provider_display_name>{{$provider}}</provider_display_name>
    </reshare>
  </post>
</XML>
