<XML>
  <post>
    <signed_retraction>
      <target_guid>{{$guid}}</target_guid>
      <target_type>{{$type}}</target_type>
      <sender_handle>{{$handle}}</sender_handle>
      <target_author_signature>{{$signature}}</target_author_signature>
    </signed_retraction>
  </post>
</XML>
