{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<XML>
  <post>
    <request>
      <sender_handle>{{$sender}}</sender_handle>
      <recipient_handle>{{$recipient}}</recipient_handle>
    </request>
  </post>
</XML>