<XML>
  <post>
    <photo>
      <guid>{{$guid}}</guid>
      <diaspora_handle>{{$handle}}</diaspora_handle>
      <public>{{$public}}</public>
      <created_at>{{$created_at}}</created_at>
      <remote_photo_path>{{$path}}</remote_photo_path>
      <remote_photo_name>{{$filename}}</remote_photo_name>
      <status_message_guid>{{$msg_guid}}</status_message_guid>
    </photo>
  </post>
</XML>
