<XML>
  <post>
    <relayable_retraction>
      <parent_author_signature>{{$parentsig}}</parent_author_signature>
      <target_guid>{{$guid}}</target_guid>
      <target_type>{{$target_type}}</target_type>
      <sender_handle>{{$handle}}</sender_handle>
      <target_author_signature>{{$authorsig}}</target_author_signature>
    </relayable_retraction>
  </post>
</XML>
