{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<h3>{{$title}}</h3>

<form action="rmagic" method="post" >

	<label for="rmagic-address" id="label-rmagic-address" class="rmagic-label">{{$desc}}</label>
	<input type="text" maxlength="255" size="32" name="address" id="rmagic-address" class="rmagic-input" value="" />

	<input type="submit" name="submit" id="rmagic-submit-button" value="{{$submit}}" />
	<div id="rmagic-submit-end" class="rmagic-field-end"></div>

</form>
