{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Milý/Milá {{$username}},

        '{{$from}}' okommentoval položku/konverzaci, kterou následujete.

-----
{{$body}}
-----

Přihlaste se na {{$siteurl}} pro zobrazení kompletní konverzace:

{{$display}}

Díky,
        {{$sitename}} administrátor
