{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Milý/Milá {{$username}},

Máte nového následovatele na {{$sitename}} -  '{{$requestor}}'.

Můžete si prohlédnout jeho/její profil na {{$url}}.

Přihlaste se na váš server k odsouhlasení nebo ignorování/zrušení žádosti.

{{$siteurl}}

S pozdravem,

        {{$sitename}} administrátor
