{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Milý/Milá {{$username}},
	Na webu {{$sitename}} byl zaregistrován požadavek na znovunastavení hesla k Vašemu účtu. Pro potvrzení této žádosti prosím klikněte na potvrzovací odkaz níže, nebo si tento odkaz zkopírujte do adresního řádku prohlížeče.  
Pokud jste o znovunastavení hesla NEŽÁDALI, prosím NEKLIKEJTE na tento odkaz a ignorujte tento e-mail nebo ho rovnou smažte.

Vaše heslo nebude změněno, dokud nebudeme mít potvrzení, že jste o tento požadavek zažádali právě Vy.

Klikněte na tento odkaz pro prověření Vaší identity:

{{$reset_link}}

Poté obdržíte další zprávu obsahující nové heslo.

Následně si toto heslo můžete změnit z vašeho účtu na stránce Nastavení.

Přihlašovací údaje jsou tato:

Adresa webu:	    {{$siteurl}}
Přihlašovací jméno: {{$email}}

S pozdravem,

        {{$sitename}} administrátor
