{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}{{$from}} Vám poslal(a) novou soukromou zprávu na {{$siteName}}.

{{$title}}

{{$textversion}}

Přihlaste se na {{$siteurl}} pro čtení a zaslání odpovědí na Vaše soukromé zprávy.

Díky,
{{$siteName}} administrátor
