{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Milý/Milá {{$username}},
        Vaše heslo bylo na Vaši žádost změněno. Prosím zaznamenejte si tuto informaci (nebo si Vaše heslo změňte na nějaké, které si budete pamatovat).
 
Vaše přihlašovací údaje jsou tato:

Adresa webu:	    {{$siteurl}}
Přihlašovací jméno: {{$email}}
Heslo:	 	    {{$new_password}}

Toto heslo si můžete změnit z vašeho účtu na stránce Nastavení poté, co se přihlásíte.

S pozdravem,
        {{$sitename}} administrátor
