{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Milý/Milá {{$username}},

        '{{$from}}' obohatil Vaši profilovou zeď.

-----
{{$body}}
-----

Přihlaste se na  {{$siteurl}} k zobrazení nebo smazání této položky:

{{$display}}

Díky,
	{{$sitename}} administrátor
