{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Kjære {{$myname}},

Du har en ny følgesvenn på {{$sitename}} - '{{$requestor}}'.

Du kan besøke profilen deres på {{$url}}. 

Vennligst logg inn på ditt sted for å godkjenne eller ignorere/avbryte forespørselen.

{{$siteurl}}

Med vennlig hilsen,

	{{$sitename}} administrator