{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Kjære {{$username}},

	Gode nyheter... '{{$fn}}' ved '{{$dfrn_url}}' har godtatt 
din forespørsel om kobling hos '{{$sitename}}'.

Dere er nå gjensidige venner og kan utveksle statusoppdateringer, bilder og e-post
uten hindringer.

Vennligst besøk din side "Kontakter" ved {{$sitename}} hvis du ønsker å gjøre  
noen endringer på denne forbindelsen. 

{{$siteurl}}

[For eksempel, så kan du lage en egen profil med informasjon som ikke er
tilgjengelig for alle - og angi visningsrettigheter til '{{$fn}}'].

Med vennlig hilsen,

	{{$sitename}} administrator

 