{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Kjære {{$username}},
	En forespørsel ble nylig mottatt hos {{$sitename}} om å tilbakestille din kontos 
passord. For å godkjenne denne forespørselen, vennligst velg bekreftelseslenken
nedenfor eller lim den inn på adresselinjen i nettleseren din. 

Hvis du IKKE har spurt om denne endringen, vennligst IKKE følg lenken
som er oppgitt og ignorer og/eller slett denne e-posten. 

Passordet ditt vil ikke bli endret med mindre vi kan forsikre oss om at du
sendte denne forespørselen. 

Følg denne lenken for å bekrefte din identitet:

{{$reset_link}}

Du vil da motta en oppfølgings melding med det nye passordet.

Du kan endre passordet på siden for dine kontoinnstillinger etter innlogging.

Innloggingsdetaljene er som følger:

Nettstedsadresse:»{{$siteurl}}
Brukernavn:»{{$email}}




Beste hilsen,
	{{$sitename}} administrator

 