{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Kjære {{$username}},
	Takk for at du registrerte deg hos {{$sitename}}. Kontoen din er opprettet. 
Innloggingsdetaljene er som følger:


Nettstedsadresse:»{{$siteurl}}
Brukernavn:»{{$email}}
Passord:»{{$password}}

Du kan endre passordet ditt på siden "Innstillinger" etter at du har logget 
inn.

Vennligst bruk litt tid til å se over de andre kontoinnstillingene på den siden.

Du vil antakelig ønske å legge til litt grunnleggende informasjon til standardprofilen din 
(på siden "Profiler") slik at folk lettere kan finne deg.

Vi anbefaler å oppgi fullt navn, legge til et profilbilde,
legge til noen "nøkkelord" for profilen (svært nyttig for å få nye venner) - og 
kanskje hvilket land du bor i, hvis du ikke ønsker å være mer spesifikk
enn det.

Vi respekterer ditt privatliv fullt ut, og ingen av disse elementene er nødvendige. 
Hvis du er ny og ikke kjenner noen her, så kan de hjelpe
deg å få noen nye og interessante venner.  


Takk og velkommen til {{$sitename}}.

Beste hilsen,
	{{$sitename}} administrator

 