{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

En ny forespørsel om brukerregistering ble mottatt hos {{$sitename}} og krever  
din godkjenning. 


Innloggingsdetaljene er som følger:

Fullt navn:»{{$username}}
Nettstedsadresse:»{{$siteurl}}
Brukernavn:»{{$email}}


For å godkjenne denne forespørselen, vennligst besøk følgende lenke:


{{$siteurl}}/regmod/allow/{{$hash}} 


For å avslå denne forespørselen og fjerne kontoen, vennligst besøk:


{{$siteurl}}/regmod/deny/{{$hash}}


Mange takk.
