{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Hei,  
jeg er {{$sitename}}.   
Friendica-utviklerne slapp nylig oppdateringen {{$update}}, 
men da jeg prøvde å installere den, gikk noe forferdelig galt.  
Dette trenger å bli fikset raskt og jeg kan ikke gjøre det alene. Vennligst kontakt en 
Friendica-utvikler hvis du ikke kan hjelpe meg på egenhånd. Databasen min er kanskje ugyldig. 

Feilmeldingen er '{{$error}}'.   

Jeg beklager,  
din Friendica-tjener hos {{$siteurl}} 