{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Dear {{$myname}},

You have a new follower at {{$sitename}} -  '{{$requestor}}'.

You may visit their profile at {{$url}}.

Please login to your site to approve or ignore/cancel the request.

{{$siteurl}}

Regards,

	{{$sitename}} administrator
