{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Dear {{$username}},

	'{{$fn}}' at '{{$dfrn_url}}' has accepted 
your connection request at '{{$sitename}}'.

	'{{$fn}}' has chosen to accept you a "fan", which restricts 
some forms of communication - such as private messaging and some profile
interactions. If this is a celebrity or community page, these settings were
applied automatically.

	'{{$fn}}' may choose to extend this into a two-way or more permissive 
relationship in the future. 

	You will start receiving public status updates from '{{$fn}}', 
which will appear on your 'Network' page at  

{{$siteurl}}

Sincerely,

	{{$sitename}} Administrator
