{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Hey, 
I'm {{$sitename}};   
The friendica developers released update {{$update}} recently, 
but when I tried to install it, something went terribly wrong.  
This needs to be fixed soon and I can't do it alone. Please contact a 
friendica developer if you can not help me on your own. My database might be invalid. 

The error message is '{{$error}}'.   

I'm sorry, 
your friendica server at {{$siteurl}}