{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

{{$username}},

'{{$from}}' har kommenterat något som du följer.

-----
{{$body}}
-----

Logga in på {{$siteurl}} för att se hela konversationen:

{{$display}}

Hälsningar,
{{$sitename}} admin

 
