{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{$username}},

'{{$fn}}' på '{{$dfrn_url}}' har accepterat din kontaktförfrågan på '{{$sitename}}'.

'{{$fn}}' har valt att acceptera dig som ett "fan" vilket innebär vissa begränsningar 
i kommunikationen mellan er - som till exempel personliga meddelanden och viss interaktion
mellan profiler. Om detta är en kändis eller en gemenskap så har dessa inställningar gjorts
per automatik.

'{{$fn}}' kan välja att utöka detta till vanlig tvåvägskommunikation eller någon annan mer 
tillåtande kommunikationsform i framtiden. 

Du kommer hädanefter att få statusuppdateringar från '{{$fn}}', 
vilka kommer att synas på din Nätverk-sida på 

{{$siteurl}}

Hälsningar,
{{$sitename}} admin
