{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}{{$username}},

En begäran om återställning av lösenord på {{$sitename}} har mottagits. 
Gå till adressen nedan för att bekräfta denna begäran. Du kan också 
klistra in länken i adressfältet i din webbläsare. 

Gå INTE till länken nedan om du INTE har begärt lösenordsåterställning. 
Då kan du ignorera det här meddelandet. 

Ditt lösenord kommer inte att återställas om vi inte kan säkerställa att du 
initierat detta.

Med den här länken kan du bekräfta din identitet:

{{$reset_link}}

Sedan kommer du att få ett meddelande med ett nytt lösenord.

Lösenordet kan sedan ändras i dina inställningar efter att du loggat in.

Detaljerna ser ut så här:

Webbplats:		{{$siteurl}}
Inloggningsnamn:	{{$email}}

Hälsningar,
{{$sitename}} admin

 