{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{$from}} har skickat ett personligt meddelande till dig på {{$siteName}}.
	
{{$title}}

{{$textversion}}
				
Logga in på {{$siteurl}} för att läsa och svara på personliga meddelanden.

Hälsningar,
{{$siteName}} admin
