{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

{{$username}},

Lösenordet har ändrats enligt din begäran. Behåll den här 
informationen om den skulle behövas i framtiden. (eller ändra lösenord 
på en gång till något som du kommer ihåg).


Här är dina inloggningsuppgifter:

Webbplats:	{{$siteurl}}
Användarnamn:	{{$email}}
Lösenord:	{{$new_password}}

När du loggat in kan du byta lösenord bland inställningarna.

Hälsningar,
{{$sitename}} admin
