{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}En registreringsförfrågan som kräver svar har mottagits 
på {{$sitename}} 


Här är inloggningsuppgifterna:

Fullständigt namn:	{{$username}}
Webbplats:		{{$siteurl}}
Användarnamn:		{{$email}}


Gå till denna adress om du vill godkänna:
{{$siteurl}}/regmod/allow/{{$hash}} 

Gå till denna adress om du vill avslå förfrågan och ta bort kontot:
{{$siteurl}}/regmod/deny/{{$hash}}

