{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}{{$myname}},

Du har just fått en kontaktförfrågan på {{$sitename}} från '{{$requestor}}'

Profilen finns på {{$url}}.

Logga in för att se hela förfrågan och godkänna eller 
avslå den.

{{$siteurl}}

Hälsningar,
{{$sitename}} admin
