{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{$username}},

'{{$from}}' har skrivit på din profilsida.

-----
{{$body}}
-----

Logga in på {{$siteurl}} för att kolla eller ta bort:

{{$display}}

Hälsningar,
{{$sitename}} admin

 
