{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Estimado/a {{$username}},

	'{{$from}}' ha comentado un elemento/conversación que estás siguiendo.

-----
{{$body}}
-----

Accede a {{$siteurl}} para ver la conversación completa:

{{$display}}


	{{$sitename}}

 

