{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Estimado/a {{$myname}},

Tienes un nuevo seguidor en {{$sitename}} -  '{{$requestor}}'.

Puedes visitar su perfil en {{$url}}.

Inicie sesión en su sitio para aprobar o rechazar/cancelar la solicitud.

{{$siteurl}}


	{{$sitename}} 
