{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Estimado/a {{$username}},

	Grandes noticias... '{{$fn}}' a '{{$dfrn_url}}' ha aceptado tu solicitud de conexión en '{{$sitename}}'.

Ahora sois amigos mutuos y podreis intercambiar actualizaciones de estado, fotos, y correo electrónico
sin restricción alguna.

Visita tu página de 'Contactos' en {{$sitename}} si desear realizar cualquier cambio en esta relación.

{{$siteurl}}

[Por ejemplo, puedes crear un perfil independiente con información que no está disponible al público en general 
- y asignar derechos de visualización a '{{$fn}}'].


	{{$sitename}}

 
