{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Has recibido un nuevo mensaje privado de '{{$from}}' en {{$siteName}}.
	
{{$title}}

{{$textversion}}
				
Accede a {{$siteurl}} para leer y responder a tus mensajes privados.

	{{$siteName}}
