{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Estimado/a {{$username}},

    Gracias por registrarte en {{$sitename}}. Tu cuenta ha sido creada.


Los datos de acceso son los siguientes:

Sitio:	{{$siteurl}}
Nombre:	{{$email}}
Contraseña:	{{$password}}


Después de acceder puedes cambiar tu contraseña en la página de "Configuración".

Toma un momento para revisar las otras configuraciones de la cuenta en esa página.


Gracias y bienvenido/a {{$sitename}}.

 
