{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Estimado/a {{$myname}},

Acabas de recibir una solicitud de conexión de '{{$requestor}}' en {{$sitename}}.

Puedes visitar su perfil en {{$url}}.

Accede a tu sitio para ver la presentación completa y aceptar o ignorar/cancelar la solicitud.

{{$siteurl}}


	{{$sitename}}
