{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Estimado/a {{$username}},

	'{{$from}}' ha escrito algo en el muro de tu perfil.

-----
{{$body}}
-----

Accede a  {{$siteurl}} para ver o borrar el elemento:

{{$display}}


	{{$sitename}}

 

