{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Kara {{$username}},

	'{{$fn}}' ĉe '{{$dfrn_url}}' akceptis 
vian kontaktpeton ĉe '{{$sitename}}'.

	'{{$fn}}' elektis vin kiel "admiranto", kio malpermesas 
kelkajn komunikilojn - ekzemple privataj mesaĝoj kaj kelkaj profilrilataj
agoj. Se tio estas konto de komunumo aŭ de eminentulo, tiaj agordoj
aŭtomate aktiviĝis.

	'{{$fn}}' eblas konverti la rilaton al ambaŭdirekta rilato 
aŭ apliki pli da permesoj. 

	Vi ekricevos publikajn afiŝojn de '{{$fn}}', 
kiuj aperos sur via 'Reto' paĝo ĉe  

{{$siteurl}}

Salutoj,

	{{$sitename}} administranto