{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Kara {{$username}},
	{{$sitename}} ricevis peton por rekomencigi vian pasvorton. 
Por konfirmi la peton, bonvolu klaki la sekvantan konfirmligilon 
aŭ alglui ĝin en la adreskampo de via retumilo. 

Se vi NE petis tiun ŝanĝon, bonvolu NE KLAKU la 
sekvantan ligilon kaj ignoru aŭ forvisu ĉi-mesaĝon. 

Ni ne ŝanĝu vian pasvorton se ni ne povas kontroli ĉu estas vi
kiu petis la ŝanĝon. 

Sekvu ĉi tion ligilon por konfirmi vian identecon:

{{$reset_link}}

Poste, vi ricevos mesaĝon enhavonte la novan pasvorton.

Vi eblas ŝangi la pasvorton ĉe viaj kontdoagordoj paĝo post ensaluti.

La akreditaĵoj estas:

Retejo:»{{$siteurl}}
Salutnomo:»{{$email}}




Salutoj,
	{{$sitename}} administranto

 