{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Kara {{$username}},
	Via pasvorto estas ŝanĝita laŭ via peto. Bonvolu konservi ĉi tiun 
informon (aŭ tuj ŝanĝu vian pasvorton al 
iu kiun vi povas memori).


Jen viaj legitimaĵoj:

Retejo:»{{$siteurl}}
Salutnomo:»{{$email}}
Pasvorto:»{{$new_password}}

Vi eblas ŝanĝi la pasvorton ĉe la paĝo Agordoj -> Konto kiam vi estas ensalutita.


Salutoj,
	{{$sitename}} administranto

 