{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Kara {{$username}},
	Dankon pro via registrado ĉe {{$sitename}}. Vian konton estas kreita. 
Jen viaj legitimaĵoj:


Retejo:»{{$siteurl}}
Salutnomo:»{{$email}}
Pasvorto:»{{$password}}

Vi eblas ŝanĝi la pasvorton ĉe la paĝo Agordoj -> Konto kiam vi estas  
ensalutita.

Bonvolu preni kelkajn momentoj por kontroli la aliajn kontaktagordojn.

Eble vi volas aldoni kelkajn bazajn informojn al via profilo 
(ĉe la paĝo "Profiloj"), tial vi troveblas al aliaj uzantoj.

Ni rekomendas agordi vian plenan noman, aldoni profilbildon,
kaj aldojo kelkajn ŝlosilvortojn (tre utila por trovi novajn amikojn) - kaj 
eble en kiu lando vi loĝas, se vi ne volas pli specifa
ol tio.

Ni tute respektas vian privatecon, kaj neniu de tiuj agordoj necesas. 
Se vi novas kaj ne konas iun ĉi tie, ili eble helpas 
vin trovi novajn kaj interesajn amikojn.  


Dankon kaj bonvenon ĉe {{$sitename}}.

Salutoj,
	{{$sitename}} administranto

 