{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Saluton! 
Mi estas {{$sitename}}.   
La programistoj de Frienda eldonis ĝisdatigon {{$update}} antaŭ ne longe, 
sed kiam mi provis instali ĝin, io terure malsukcesis.  
Tio tuj bezonas riparon kaj mi ne povas fari ĝin sole. Bonvolu kontakti 
Friendica programistion se vi ne povas helpi vin mem. Mia datumbazo eble ne plu validas. 

La erarmesaĝo estas '{{$error}}'.   

Mi bedaŭras, 
via Friendica servilo ĉe {{$siteurl}}