{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Hallo {{$username}},

'{{$from}}' hat einen Pinnwandeintrag kommentiert dem du auch folgst.

-----
{{$body}}
-----

Um die gesamte Konversation zu sehen melde dich bitte bei {{$siteurl}} an:

{{$display}}

Danke für die Aufmerksamkeit
        {{$sitename}} Administrator
 

