{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Hallo {{$myname}},

Du hast einen neuen Anhänger auf {{$sitename}} -  '{{$requestor}}'.

Du kannst das Profil unter {{$url}} besuchen.

Bitte melde dich an um die Anfrage zu bestätigen oder sie zu ignorieren bzw. abzulehnen.

{{$siteurl}}

beste Grüße,

	{{$sitename}} Administrator