{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Hallo {{$username}},
	Auf {{$sitename}} wurde eine Anfrage zum Zurücksetzen deines 
Passworts empfangen. Um diese zu bestätigen folge bitte dem Link
weiter unten oder kopiere ihn in die Adressleiste deines Browsers. 

Wenn du die Anfrage NICHT gesendet haben solltest, dann IGNORIERE
bitte diese Mail und den Link. 

Dein Passwort wird nicht geändert werden solange wir nicht überprüfen
konnten, dass du die Anfrage gestellt hast. 

Folge diesem Link um deine Identität zu verifizieren:

{{$reset_link}}

Du wirst eine weitere Email erhalten mit dem neuen Passwort.

Das Passwort kannst du anschließend wie gewohnt in deinen Account Einstellungen ändern.

Die Login-Details sind die folgenden:

Adresse der Seite:	{{$siteurl}}
Login Name:	{{$email}}




Grüße,
	{{$sitename}} Administrator

 