{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Du hast eine neue private Nachricht von '{{$from}}' auf '{{$siteName}}' erhhalten.
	
{{$title}}

{{$textversion}}

Bitte melde dich unter {{$siteurl}} an um deine privaten Nachrichte zu lesen und zu
beantworten.

Viele Grüße,
{{$siteName}} Administrator
