{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Hallo {{$myname}},

du hast eine Kontaktanfrage von '{{$requestor}}' auf {{$sitename}} 

erhalten.

Du kannst sein/ihr Profil unter {{$url}} finden.

Bitte melde dich an um die komplette Vorstellung einzusehen 
und die Anfrage zu bestätigen oder zu ignorieren oder abzulehnen.

{{$siteurl}}

Beste Grüße,

	{{$sitename}} Administrator