{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Hi, 
ich bin {{$sitename}}.   
Die friendica Entwickler haben jüngst Update {{$update}} veröffentlicht, 
aber als ich versucht habe es zu installieren ist etwas schrecklich schief gegangen.  
Das sollte schnellst möglichst behoben werden und ich kann das nicht alleine machen. 
Bitte wende dich an einen friendica Entwickler, falls du mir nicht alleine helfen kannst. Meine Datenbank könnte unbrauchbar sein. 

Die Fehlermeldung lautet '{{$error}}'.   

Tut mir Leid! 
Deine friendica Instanz auf {{$siteurl}}