{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Hallo {{$username}},

'{{$from}}' hat etwas auf deiner Profilwand gepostet.

-----
{{$body}}
-----

Bitte melde dich unter {{$siteurl}} an um den Eintrag anzusehen oder zu löschen.

{{$display}}

Besten Dank!
        {{$sitename}} Administrator

 

