{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Hallo {{$username}},

        '{{$from}}' hat etwas auf deiner Pinnwand gepostet.

-----
{{$body}}
-----

Bitte melde dich auf {{$siteurl}} an um den Beitrag anzusehen oder ihn zu löschen:

{{$display}}

Besten Dank!
    {{$sitename}} Administrator

 

