{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Cher(e) {{$username}},

	« {{$from}} » a commenté un éléŽment ou une conversation que vous suivez.

-----
{{$body}}
-----

Connectez-vous à {{$siteurl}} si vous souhaitez voir la conversation complète :

{{$display}}

Merci,
	L'administrateur de {{$sitename}}