{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Cher(e) {{$myname}},

Une nouvelle personne - {{$requestor}} - vous suit désormais sur {{$sitename}}.

Vous pouvez consulter son profil sur {{$url}}.

Merci de vous connecter à votre site pour approuver ou ignorer/annuler cette demande.

{{$siteurl}}

Cordialement,

	l'administrateur de {{$sitename}}
