{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Cher(e) {{$username}},

	Grande nouvelle… « {{$fn}} » (de « {{$dfrn_url}} ») a accepté votre 
demande de connexion à « {{$sitename}} ».

Vous êtes désormais dans une relation réciproque et pouvez échanger des 
photos, des humeurs et des messages sans restriction.

Merci de visiter votre page « Contacts » sur {{$sitename}} pour toute 
modification que vous souhaiteriez apporter à cette relation.

{{$siteurl}}

[Par exemple, vous pouvez créer un profil spécifique avec des informations
cachées au grand public - et ainsi assigner des droits privilégiés à 
« {{$fn}} »]/

Sincèremment,

	l'administrateur de {{$sitename}}

 
