{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Cher(e) {{$username}},

	« {{$fn}} » du site « {{$dfrn_url}} » a accepté votre
demande de mise en relation sur « {{$sitename}} ».

	« {{$fn}} » a décidé de vous accepter comme « fan », ce qui restreint
certains de vos moyens de communication - tels que les messages privés et
certaines interactions avec son profil. S'il s'agit de la page d'une
célébrité et/ou communauté, ces réglages ont été définis automatiquement.

	« {{$fn}} » pourra choisir d'étendre votre relation à quelque chose de 
plus permissif dans l'avenir.

	Vous allez commencer à recevoir les mises à jour publiques du 
statut de « {{$fn}} », lesquelles apparaîtront sur votre page « Réseau » sur

{{$siteurl}}

Sincèrement votre,

	l'administrateur de {{$sitename}}
