{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{$from}} vous a envoyé un message à {{$siteName}}.
	
{{$title}}

{{$textversion}}

Veuillez ouvrir une session sur {{$siteurl}} pour lire et répondre à vos messages privés.

Merci,
{{$siteName}} Administrateur
