{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Cher(e) {{$username}},

	Merci de votre inscription à {{$sitename}}. Votre compte a été créé.
Les informations de connexion sont les suivantes :

Site :			{{$siteurl}}
Pseudo/Courriel :	{{$email}}
Mot de passe :		{{$password}}

Vous pouvez changer de mot de passe dans la page des « Réglages » de votre compte,
après connexion.

Merci de prendre quelques minutes pour découvrir les autres réglages disponibles
sur cette page.

Merci, et bienvenue sur {{$sitename}}.

Sincèrement votre,
	l'administrateur de {{$sitename}}

 
