{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Une nouvelle demande d'inscription a été reçue sur {{$sitename}}, et elle
nécessite votre approbation.


Les informations de connexion sont les suivantes :

Nom complet :		{{$username}}
Site :			{{$siteurl}}
Pseudo/Courriel :	{{$email}}


Pour approuver cette demande, merci de suivre le lien :


{{$siteurl}}/regmod/allow/{{$hash}}


Pour rejeter cette demande et supprimer le compte associé, 
merci de suivre le lien :


{{$siteurl}}/regmod/deny/{{$hash}}


En vous remerçiant.

