{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Cher(e) {{$username}},

	« {{$from}} » a posté quelque chose sur le mur de votre profil.

-----
{{$body}}
-----

Connectez-vous à {{$siteurl}} pour voir et/ou supprimer l'élément :

{{$display}}

Merci,
	l'administrateur de {{$sitename}}

 

