#!/bin/sh -f


if [ $# -ne 2 ]; then
	echo usage: $0 repo_url nickname
	exit 1
fi

mkdir -p extend/theme/$2
git clone $1 extend/theme/$2
if [ $? -ne 0 ]; then
	exit $?
fi

filelist=(`ls extend/theme/$2`)

cd view/theme
for a in "${filelist[@]}" ; do
	base=`basename $a`
	if [ $base = '.git' ]; then
#		echo 'ignoring git'
		continue;
	fi
	if [ ! -d ../../extend/theme/$2/$base ]; then
#		echo $a 'not a directory'
		continue;
	fi
	if [ -x $base ]; then
#		echo $base 'file exists'
		continue;
	fi

	echo linking $base 
	ln -s ../../extend/theme/$2/$base $base
done


