#!/bin/sh -f

if [ $# -ne 2 ]; then
	echo usage: $0 repo_url nickname
	exit 1
fi

mkdir -p extend/addon/$2
mkdir addon > /dev/null 2>&1
git clone $1 extend/addon/$2
if [ $? -ne 0 ]; then
	exit $?
fi

filelist=(`ls extend/addon/$2`)


cd addon
for a in "${filelist[@]}" ; do
	base=`basename $a`
	if [ $base = '.git' ]; then
#		echo 'ignoring git'
		continue;
	fi
	if [ ! -d ../extend/addon/$2/$base ]; then
#		echo $a 'not a directory'
		continue;
	fi
	if [ -x $base ]; then
#		echo $base 'file exists'
		continue;
	fi

	echo linking $base 

	ln -s ../extend/addon/$2/$base $base
done


