#!/usr/bin/env php
<?php

// Red pconfig utility

require_once('include/cli_startup.php');

cli_startup();

if($argc > 4) {
	set_pconfig($argv[1],$argv[2],$argv[3],$argv[4]);
	echo "pconfig[{$argv[1]}][{$argv[2]}][{$argv[3]}] = " . get_pconfig($argv[1],$argv[2],$argv[3]) . "\n";
}

if($argc == 4) {
	echo "pconfig[{$argv[1]}][{$argv[2]}][{$argv[3]}] = " . get_pconfig($argv[1],$argv[2],$argv[3]) . "\n";
}

if($argc == 3) {
	load_pconfig($argv[1],$argv[2]);
	foreach($a->config[$argv[1]][$argv[2]] as $k => $x) {
		echo "pconfig[{$argv[1]}][{$argv[2]}][{$k}] = " . $x . "\n";
	}
}

if($argc == 2) {
	$r = q("select * from pconfig where uid = " . intval($argv[1]));
	if($r) {
		foreach($r as $rr) {
			echo "pconfig[{$rr['uid']}][{$rr['cat']}][{$rr['k']}] = " . $rr['v'] . "\n";
		}
	}
}

