#!/bin/sh -f


if [ $# -ne 1 ]; then
	echo usage: $0 repository
	echo "Repositories:"
	ls extend/theme
	exit 1
fi

cd extend/theme/$1

if [ -d .git ] ; then
	git pull
fi

cd ../../..

filelist=(`ls extend/theme/$1`)

cd view/theme

for a in "${filelist[@]}" ; do
	base=`basename $a`
	if [ $base = '.git' ]; then
#		echo 'ignoring git'
		continue;
	fi
	if [ ! -d ../../extend/theme/$1/$base ]; then
#		echo $a 'not a directory'
		continue;
	fi
	if [ -x $base ]; then
#		echo $base 'file exists'
		continue;
	fi

	echo linking $base 
	ln -s ../../extend/theme/$1/$base $base
done


