{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Apreciat/da {{$username}},

	'{{$from}}' ha comentat un element/conversació que estàs seguint.

-----
{{$body}}
-----

Accedeix a {{$siteurl}} per a veure la conversa completa:

{{$display}}


	{{$sitename}}

 

