{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}Has rebut un nou missatge privat de '{{$from}}' en {{$siteName}}.
	
{{$title}}

{{$textversion}}
				
Accedeix a {{$siteurl}} per a llegir i respondre als teus missatges privats.

	{{$siteName}}
