{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Apreciat/da {{$username}},

	'{{$from}}' ha escrit quelcom en el mur del teu perfil.

-----
{{$body}}
-----

Accedeix a  {{$siteurl}} per a veure o esborrar l'element:

{{$display}}


	{{$sitename}}

 

