{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{include file="field_select.tpl" field=$colour}}

{{include file="field_input.tpl" field=$font_size}}

{{include file="field_input.tpl" field=$line_height}}

{{include file="field_select.tpl" field=$shadow}}

{{include file="field_select.tpl" field=$navcolour}}

{{include file="field_select.tpl" field=$displaystyle}}

{{include file="field_input.tpl" field=$linkcolour}}

{{include file="field_select.tpl" field=$iconset}}

{{include file="field_select.tpl" field=$shiny}}

<div class="settings-submit-wrapper">
	<input type="submit" value="{{$submit}}" class="settings-submit" name="redbasic-settings-submit" />
</div>
