{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<users type="array">
	{{foreach $users as $user}}
	{{include file="api_user_xml.tpl"}}
	{{/foreach}}
</users>
