{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<dfrn:mail>

	<dfrn:sender>
		<dfrn:name>{{$name}}</dfrn:name>
		<dfrn:uri>{{$profile_page}}</dfrn:uri>
		<dfrn:avatar>{{$thumb}}</dfrn:avatar>
	</dfrn:sender>

	<dfrn:id>{{$item_id}}</dfrn:id>
	<dfrn:in-reply-to>{{$parent_id}}</dfrn:in-reply-to>
	<dfrn:sentdate>{{$created}}</dfrn:sentdate>
	<dfrn:subject>{{$subject}}</dfrn:subject>
	<dfrn:content>{{$content}}</dfrn:content>

</dfrn:mail>

