{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<dfrn:suggest>

	<dfrn:url>{{$url}}</dfrn:url>
	<dfrn:name>{{$name}}</dfrn:name>
	<dfrn:photo>{{$photo}}</dfrn:photo>
	<dfrn:request>{{$request}}</dfrn:request>
	<dfrn:note>{{$note}}</dfrn:note>

</dfrn:suggest>

