{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<decrypted_hdeader>
  <iv>{{$inner_iv}}</iv>
  <aes_key>{{$inner_key}}</aes_key>
  <author>
    <name>{{$author_name}}</name>
    <uri>{{$author_uri}}</uri>
  </author>
</decrypted_header>
