<XML>
  <post>
    <relayable_retraction>
      <target_type>{{$type}}</target_type>
      <target_guid>{{$guid}}</target_guid>
      <target_author_signature>{{$signature}}</target_author_signature>
      <sender_handle>{{$handle}}</sender_handle>
    </relayable_retraction>
  </post>
</XML>
