{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

<div class="directory-item lframe" id="directory-item-{{$id}}" >
	<div class="contact-photo-wrapper" id="directory-photo-wrapper-{{$id}}" > 
		<div class="contact-photo" id="directory-photo-{{$id}}" >
			<a href="{{$profile_link}}" class="directory-profile-link" id="directory-profile-link-{{$id}}" ><img class="directory-photo-img" src="{{$photo}}" alt="{{$alt_text}}" title="{{$alt_text}}" /></a>
		</div>
	</div>

	<div class="contact-name" id="directory-name-{{$id}}">{{$name}}</div>
	<div class="contact-details">{{$details}}</div>
</div>
