{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}<script>
$(document).ready(function() {
	$(".comment-edit-wrapper textarea").contact_autocomplete(baseurl+"/acl");
	// make auto-complete work in more places
	$(".wall-item-comment-wrapper textarea").contact_autocomplete(baseurl+"/acl");
});
</script>

