{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{$preamble}}
	
{{$title}}

{{$textversion}}
				
{{$tsitelink}}
{{$titemlink}}

{{$thanks}}
{{$site_admin}}

