{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}{{$tabs}}
<h2>{{$title}}</h2>

<div id="new-event-link"><a href="{{$new_event.0}}" >{{$new_event.1}}</a></div>

<div id="events-calendar"></div>
