{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
	
	<div class='field input openid'>
		<label for='id_{{$field.0}}'>{{$field.1}}</label>
		<input name='{{$field.0}}' id='id_{{$field.0}}' value="{{$field.2}}">
		<span class='field_help'>{{$field.3}}</span>
	</div>
