{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
	
	<div class='field checkbox'>
		<label for='id_{{$field.0}}'>{{$field.1}}</label>
		<input type="checkbox" name='{{$field.0}}' id='id_{{$field.0}}' value="1" {{if $field.2}}checked="checked"{{/if}}>
		<span class='field_help'>{{$field.3}}</span>
	</div>
