{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}{{include file="field_combobox.tpl"}}
<div class="settings-submit-wrapper" >
	<input id="filer_save" type="button" class="settings-submit" value="{{$submit}}" />
</div>
