{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<h1>{{$title}}</h1>
<h2>{{$pass}}</h2>


{{if $status}}
<h3 class="error-message">{{$status}}</h3>
{{/if}}

{{$text}}
