{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}<h3>{{$title}}</h3>

<p id="lostpass-desc">
{{$desc}}
</p>

<form action="lostpass" method="post" >
<div id="login-name-wrapper">
        <label for="login-name" id="label-login-name">{{$name}}</label>
        <input type="text" maxlength="60" name="login-name" id="login-name" value="" />
</div>
<div id="login-extra-end"></div>
<div id="login-submit-wrapper" >
        <input type="submit" name="submit" id="lostpass-submit-button" value="{{$submit}}" />
</div>
<div id="login-submit-end"></div>
</form>

