{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

<h1>{{$notif_header}}</h1>

{{include file="common_tabs.tpl"}}

<div class="notif-network-wrapper">
	{{$notif_content}}
</div>
