{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}<?xml version='1.0' encoding='UTF-8'?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
        
    <Subject>{{$base}}</Subject>

    <Property 
        type="http://www.oexchange.org/spec/0.8/prop/vendor">Friendika</Property>
    <Property 
        type="http://www.oexchange.org/spec/0.8/prop/title">Friendika Social Network</Property>
    <Property 
        type="http://www.oexchange.org/spec/0.8/prop/name">Friendika</Property>
    <Property 
        type="http://www.oexchange.org/spec/0.8/prop/prompt">Send to Friendika</Property>

    <Link 
        rel="icon" 
        href="{{$base}}/images/friendika-16.png"
        type="image/png" 
        />

    <Link 
        rel="icon32" 
        href="{{$base}}/images/friendika-32.png"
        type="image/png" 
        />

    <Link 
        rel= "http://www.oexchange.org/spec/0.8/rel/offer" 
        href="{{$base}}/oexchange"
        type="text/html" 
        />
</XRD>

