{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}<h1>{{$header}}</h1>
<p id="profile-listing-desc" class="button" >
<a href="profile_photo" >{{$chg_photo}}</a>
</p>
<div id="profile-listing-new-link-wrapper" class="button" >
<a href="{{$cr_new_link}}" id="profile-listing-new-link" title="{{$cr_new}}" >{{$cr_new}}</a>
</div>

