The Red Matrix: view/theme/apw/php/style.php File Reference
style.php File Reference
Variables
$uid = get_theme_uid()
if ($uid) load_pconfig($uid
$x = splitFilename($font)
$fname = $x[0]
$fext = $x[1]
if(file_exists('view/theme/apw/font/'.$fname.
'i.'.$fext)) if(file_exists('view/theme/apw/font/'.$fname.
'b.'.$fext)) $strongmacro = ''
$obliquemacro = ''
if($nav) $sectiontop = "28px"
$iconsize = "16px"
$navheight = "27px"
$showlock = "block"
Variable Documentation
$fext = $x[1]
$fname = $x[0]
Referenced by RedMatrix\RedDAV\RedFile\put(), and reload_plugins().
$iconsize = "16px"
$navheight = "27px"
$obliquemacro = ''
if ($nav) $sectiontop = "28px"
$showlock = "block"
if (file_exists('view/theme/apw/font/'.$fname. 'i.'.$fext)) if (file_exists('view/theme/apw/font/'.$fname. 'b.'.$fext)) $strongmacro = ''
$uid = get_theme_uid()
Referenced by admin_page_channels(), admin_page_channels_post(), admin_page_users(), admin_page_users_post(), all_friends(), app_destroy(), app_install(), app_installed(), app_list(), blocks_content(), build_sync_packet(), catblock(), chat_message(), chatroom_list(), chatroom_list_count(), check_item_source(), check_list_permissions(), common_friends(), common_friends_zcid(), count_all_friends(), count_common_friends(), count_common_friends_zcid(), del_pconfig(), delete_imported_item(), diaspora_get_contact_by_handle(), drop_items(), editblock_content(), editlayout_content(), editwebpage_content(), event_addtocal(), events_post(), feature_enabled(), first_post_date(), fix_attached_photo_permissions(), fix_private_photos(), follow_init(), get_all_perms(), get_channel_default_perms(), get_pconfig(), get_theme_uid(), get_things(), get_words(), group_add(), group_add_member(), group_byname(), group_rec_byhash(), group_rmv(), group_rmv_member(), groups_containing(), handle_feed(), import_channel_photo(), item_add_cid(), item_expire(), item_post(), item_remove_cid(), item_store_update(), items_fetch(), layouts_content(), linkify_tags(), list_post_dates(), load_contact_links(), load_pconfig(), local_dir_update(), FKOAuth1\loginUser(), menu_add_item(), menu_content(), menu_del_item(), menu_delete(), menu_delete_id(), menu_edit_item(), menu_fetch(), menu_post(), mini_group_select(), mitem_content(), mitem_init(), mitem_post(), mood_init(), new_contact(), notifier_run(), pdl_selector(), perm_is_allowed(), photo_init(), poke_init(), posted_dates(), private_messages_list(), remove_community_tag(), send_message(), service_class_allows(), service_class_fetch(), set_pconfig(), Conversation\set_profile_owner(), photo_driver\store(), store_item_tag(), suggestion_query(), tag_deliver(), tagadelic(), tagblock(), tgroup_check(), update_feed_item(), webpages_content(), widget_archive(), widget_follow(), widget_item(), widget_tagcloud(), wtagblock(), and zot_feed().
$x = splitFilename($font)
Referenced by Template\_replcb_for(), Template\_replcb_if(), account_remove(), acl_init(), activity_sanitise(), admin_page_channels(), admin_page_themes(), advanced_profile(), aes_encapsulate(), api_group_members(), api_login(), app_decode(), app_install(), app_list(), app_render(), app_store(), app_update(), apps_content(), argv(), array_sanitise(), attach_change_permissions(), attach_delete(), attach_store(), autoname(), bb_parse_crypt(), bbcode(), block_content(), blocks_content(), bookmark_add(), bookmarks_content(), build_sync_packet(), change_channel(), channel_content(), chat_content(), chat_message(), chat_post(), chatroom_create(), chatroom_enter(), chatsvc_content(), chatsvc_init(), chatsvc_post(), check_config(), check_form_security_token(), check_item_source(), check_list_permissions(), check_upstream_directory(), check_webbie(), RedMatrix\RedDAV\RedDirectory\childExists(), cloud_init(), common_init(), connedit_content(), construct_page(), consume_feed(), conversation(), RedMatrix\RedDAV\RedDirectory\createFile(), photo_gd\cropImage(), photo_imagick\cropImage(), dav_init(), decode_tags(), deliver_run(), diaspora_comment(), diaspora_like(), diaspora_mention_callback(), diaspora_request(), dir_tagadelic(), directory_content(), directory_run(), discover_by_url(), discover_by_webbie(), display_content(), downgrade_accounts(), editblock_content(), editlayout_content(), editwebpage_content(), email_header_encode(), encode_item(), encode_mail(), dba_postgres\escape(), event_store_item(), events_post(), expand_groups(), expire_run(), externals_run(), feature_enabled(), fetch_post_tags(), fetch_xrd_links(), filer_content(), find_xchan_in_array(), findpeople_widget(), fix_private_photos(), fix_system_urls(), photo_gd\flip(), foofoo(), fsuggest_post(), get_all_perms(), get_diaspora_reshare_xml(), get_directory_realm(), get_file_activity_object(), get_item_elements(), get_mail_elements(), get_mentions(), get_online_status(), get_profile_elements(), get_profile_fields_advanced(), get_profile_fields_basic(), get_role_perms(), get_system_apps(), get_terms_oftype(), get_theme_uid(), get_things(), RedMatrix\RedDAV\RedDirectory\getChild(), RedMatrix\RedDAV\RedDirectory\getDir(), RedMatrix\RedDAV\RedDirectory\getQuotaInfo(), gprobe_run(), handle_feed(), hcard_init(), help_content(), hostxrd_init(), ids_to_querystr(), impel_init(), import_author_diaspora(), import_author_rss(), import_author_unknown(), import_author_xchan(), import_author_zot(), import_directory_keywords(), import_directory_profile(), import_post(), import_site(), import_xchan(), invite_content(), invite_post(), item_post(), item_remove_cid(), item_store(), items_fetch(), json_decode_plus(), json_return_and_die(), layouts_content(), legal_webbie(), linkify_tags(), locs_content(), FKOAuth1\loginUser(), magic_init(), mail_post(), manage_content(), mark_orphan_hubsxchans(), match_content(), menu_content(), menu_delete_id(), menu_fetch(), menu_render(), mimetype_select(), nav(), navbar_complete(), netgrowth_content(), network_content(), new_channel_init(), new_contact(), notification(), notifications_off(), notifications_on(), notifier_run(), oembed_fetch_url(), onedirsync_run(), onepoll_run(), openid_content(), page_init(), parse_app_description(), parse_xml_string(), pdledit_content(), pemtome(), perm_is_allowed(), photos_list_photos(), photos_post(), ping_init(), poco_load(), poller_run(), post_init(), post_post(), prate_post(), preg_heart(), prepare_body(), print_template(), private_messages_list(), proc_run(), process_channel_sync_delivery(), process_location_delivery(), process_mail_delivery(), process_rating_delivery(), profile_init(), profile_load(), profile_photo_post(), profiles_content(), profiles_init(), prune_hub_reinstalls(), public_recips(), pubrsatome(), RedMatrix\RedDAV\RedFile\put(), dba_mysql\q(), dba_mysqli\q(), dba_postgres\q(), random_profile(), randprof_init(), red_item_new(), RedCollectionData(), RedFileData(), reflect_comment_store(), reflect_find_user(), reflect_photo_callback(), remote_online_status(), remove_community_tag(), remove_obsolete_hublocs(), rpost_content(), photo_driver\save(), scrape_feed(), scrape_vcard(), search_ac_init(), search_content(), send_status_notifications(), service_limits_content(), set_linkified_perms(), share_init(), share_unshield(), sharedwithme_content(), site_default_perms(), smilies(), sources_content(), sslify_init(), photo_driver\store(), store_diaspora_comment_sig(), string_splitter(), stringify_array_elms(), sync_directories(), sync_locations(), tag_deliver(), tagadelic(), tagrm_content(), tagrm_post(), theme_status(), thing_content(), toggle_theme(), update_channels_active_halfyear_stat(), update_channels_active_monthly_stat(), update_directory_entry(), update_imported_item(), upgrade_bool_message(), upgrade_message(), valid_email(), RedMatrix\RedDAV\RedBasicAuth\validateUserPass(), webpages_content(), what_next(), widget_affinity(), widget_bookmarkedchats(), widget_suggestedchats(), widget_suggestions(), xchan_query(), xmlify(), zfinger_init(), zot_build_packet(), zot_encode_locations(), zot_process_response(), zot_refresh(), zot_register_hub(), and zotfeed_init().
if (($schema)&&($schema!= '---')) if(!$schema||($schema== '---'))