The Red Matrix: boot.php File Reference
boot.php File Reference
Classes
class App
Functions
startup ()
get_app ()
x ($s, $k=NULL)
system_unavailable ()
clean_urls ()
z_path ()
z_root ()
absurl ($path)
is_ajax ()
check_config (&$a)
fix_system_urls ($oldurl, $newurl)
login ($register=false, $form_id= 'main-login', $hiddens=false)
killme ()
goaway ($s)
get_account_id ()
local_user ()
remote_user ()
notice ($s)
info ($s)
get_max_import_size ()
profile_load (&$a, $nickname, $profile=0)
profile_create_sidebar (&$a)
profile_sidebar ($profile, $block=0)
get_birthdays ()
get_events ()
proc_run ($cmd)
current_theme ()
current_theme_url ()
z_birthday ($dob, $tz, $format="Y-m-d H:i:s")
is_site_admin ()
load_contact_links ($uid)
profile_tabs ($a, $is_owner=False, $nickname=Null)
get_my_url ()
get_my_address ()
zid_init (&$a)
zid ($s, $force=false)
build_querystring ($params, $name=null)
argc ()
argv ($x)
dba_timer ()
get_observer_hash ()
curPageURL ()
construct_page (&$a)
appdirpath ()
Variables
const RED_PLATFORM 'Red'
const RED_VERSION trim(file_get_contents('version.inc')) . 'R'
const ZOT_REVISION 1
const DB_UPDATE_VERSION 1042
const EOL '<br />' . "\r\n"
const ATOM_TIME 'Y-m-d\TH:i:s\Z'
const DIRECTORY_MODE_NORMAL 0x0000
const DIRECTORY_MODE_PRIMARY 0x0001
const DIRECTORY_MODE_SECONDARY 0x0002
const DIRECTORY_MODE_STANDALONE 0x0100
const DIRECTORY_REALM 'RED_GLOBAL'
const DIRECTORY_FALLBACK_MASTER 'https://zothub.com'
const JPEG_QUALITY 100
const PNG_QUALITY 8
const LANGUAGE_DETECT_MIN_LENGTH 128
const LANGUAGE_DETECT_MIN_CONFIDENCE 0.01
const MAX_IMAGE_LENGTH -1
const DEFAULT_DB_ENGINE 'MyISAM'
const SSL_POLICY_NONE 0
const SSL_POLICY_FULL 1
const SSL_POLICY_SELFSIGN 2
const LOGGER_NORMAL 0
const LOGGER_TRACE 1
const LOGGER_DEBUG 2
const LOGGER_DATA 3
const LOGGER_ALL 4
const REGISTER_CLOSED 0
const REGISTER_APPROVE 1
const REGISTER_OPEN 2
const CONTACT_IS_FOLLOWER 1
const CONTACT_IS_SHARING 2
const CONTACT_IS_FRIEND 3
const UPDATE_SUCCESS 0
const UPDATE_FAILED 1
const PAGE_NORMAL 0x0000
const PAGE_HIDDEN 0x0001
const PAGE_AUTOCONNECT 0x0002
const PAGE_APPLICATION 0x0004
const PAGE_DIRECTORY_CHANNEL 0x0008
const PAGE_REMOVED 0x8000
const NETWORK_DFRN 'dfrn'
const NETWORK_ZOT 'zot!'
const NETWORK_OSTATUS 'stat'
const NETWORK_FEED 'feed'
const NETWORK_DIASPORA 'dspr'
const NETWORK_MAIL 'mail'
const NETWORK_MAIL2 'mai2'
const NETWORK_FACEBOOK 'face'
const NETWORK_LINKEDIN 'lnkd'
const NETWORK_XMPP 'xmpp'
const NETWORK_MYSPACE 'mysp'
const NETWORK_GPLUS 'goog'
const NETWORK_PHANTOM 'unkn'
const PERMS_R_STREAM 0x0001
const PERMS_R_PROFILE 0x0002
const PERMS_R_PHOTOS 0x0004
const PERMS_R_ABOOK 0x0008
const PERMS_W_STREAM 0x0010
const PERMS_W_WALL 0x0020
const PERMS_W_TAGWALL 0x0040
const PERMS_W_COMMENT 0x0080
const PERMS_W_MAIL 0x0100
const PERMS_W_PHOTOS 0x0200
const PERMS_W_CHAT 0x0400
const PERMS_A_DELEGATE 0x0800
const PERMS_R_STORAGE 0x1000
const PERMS_W_STORAGE 0x2000
const PERMS_R_PAGES 0x4000
const PERMS_W_PAGES 0x8000
const PERMS_PUBLIC 0x0001
const PERMS_NETWORK 0x0002
const PERMS_SITE 0x0004
const PERMS_CONTACTS 0x0008
const PERMS_SPECIFIC 0x0080
const ABOOK_FLAG_BLOCKED 0x0001
const ABOOK_FLAG_IGNORED 0x0002
const ABOOK_FLAG_HIDDEN 0x0004
const ABOOK_FLAG_ARCHIVED 0x0008
const ABOOK_FLAG_PENDING 0x0010
const ABOOK_FLAG_SELF 0x0080
const MAIL_DELETED 0x0001
const MAIL_REPLIED 0x0002
const MAIL_ISREPLY 0x0004
const MAIL_SEEN 0x0008
const MAIL_RECALLED 0x0010
const ATTACH_FLAG_DIR 0x0001
const ATTACH_FLAG_OS 0x0002
const MAX_LIKERS 75
const ZCURL_TIMEOUT (-1)
const NOTIFY_INTRO 0x0001
const NOTIFY_CONFIRM 0x0002
const NOTIFY_WALL 0x0004
const NOTIFY_COMMENT 0x0008
const NOTIFY_MAIL 0x0010
const NOTIFY_SUGGEST 0x0020
const NOTIFY_PROFILE 0x0040
const NOTIFY_TAGSELF 0x0080
const NOTIFY_TAGSHARE 0x0100
const NOTIFY_POKE 0x0200
const NOTIFY_SYSTEM 0x8000
const HUBLOC_FLAGS_PRIMARY 0x0001
const HUBLOC_FLAGS_UNVERIFIED 0x0002
const XCHAN_FLAGS_HIDDEN 0x0001
const TERM_UNKNOWN 0
const TERM_HASHTAG 1
const TERM_MENTION 2
const TERM_CATEGORY 3
const TERM_PCATEGORY 4
const TERM_FILE 5
const TERM_SAVEDSEARCH 6
const TERM_OBJ_POST 1
const TERM_OBJ_PHOTO 2
const NAMESPACE_ZOT 'http://purl.org/zot'
const NAMESPACE_DFRN 'http://purl.org/macgirvin/dfrn/1.0'
const NAMESPACE_THREAD 'http://purl.org/syndication/thread/1.0'
const NAMESPACE_TOMB 'http://purl.org/atompub/tombstones/1.0'
const NAMESPACE_ACTIVITY 'http://activitystrea.ms/spec/1.0/'
const NAMESPACE_ACTIVITY_SCHEMA 'http://activitystrea.ms/schema/1.0/'
const NAMESPACE_MEDIA 'http://purl.org/syndication/atommedia'
const NAMESPACE_SALMON_ME 'http://salmon-protocol.org/ns/magic-env'
const NAMESPACE_OSTATUSSUB 'http://ostatus.org/schema/1.0/subscribe'
const NAMESPACE_GEORSS 'http://www.georss.org/georss'
const NAMESPACE_POCO 'http://portablecontacts.net/spec/1.0'
const NAMESPACE_FEED 'http://schemas.google.com/g/2010#updates-from'
const NAMESPACE_OSTATUS 'http://ostatus.org/schema/1.0'
const NAMESPACE_STATUSNET 'http://status.net/schema/api/1/'
const NAMESPACE_ATOM1 'http://www.w3.org/2005/Atom'
const ACTIVITY_LIKE NAMESPACE_ACTIVITY_SCHEMA . 'like'
const ACTIVITY_DISLIKE NAMESPACE_ZOT . '/activity/dislike'
const ACTIVITY_OBJ_HEART NAMESPACE_ZOT . '/activity/heart'
const ACTIVITY_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'make-friend'
const ACTIVITY_REQ_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'request-friend'
const ACTIVITY_UNFRIEND NAMESPACE_ACTIVITY_SCHEMA . 'remove-friend'
const ACTIVITY_FOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'follow'
const ACTIVITY_UNFOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'stop-following'
const ACTIVITY_JOIN NAMESPACE_ACTIVITY_SCHEMA . 'join'
const ACTIVITY_POST NAMESPACE_ACTIVITY_SCHEMA . 'post'
const ACTIVITY_UPDATE NAMESPACE_ACTIVITY_SCHEMA . 'update'
const ACTIVITY_TAG NAMESPACE_ACTIVITY_SCHEMA . 'tag'
const ACTIVITY_FAVORITE NAMESPACE_ACTIVITY_SCHEMA . 'favorite'
const ACTIVITY_POKE NAMESPACE_ZOT . '/activity/poke'
const ACTIVITY_MOOD NAMESPACE_ZOT . '/activity/mood'
const ACTIVITY_OBJ_COMMENT NAMESPACE_ACTIVITY_SCHEMA . 'comment'
const ACTIVITY_OBJ_NOTE NAMESPACE_ACTIVITY_SCHEMA . 'note'
const ACTIVITY_OBJ_PERSON NAMESPACE_ACTIVITY_SCHEMA . 'person'
const ACTIVITY_OBJ_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'photo'
const ACTIVITY_OBJ_P_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'profile-photo'
const ACTIVITY_OBJ_ALBUM NAMESPACE_ACTIVITY_SCHEMA . 'photo-album'
const ACTIVITY_OBJ_EVENT NAMESPACE_ACTIVITY_SCHEMA . 'event'
const ACTIVITY_OBJ_GROUP NAMESPACE_ACTIVITY_SCHEMA . 'group'
const ACTIVITY_OBJ_TAGTERM NAMESPACE_ZOT . '/activity/tagterm'
const ACTIVITY_OBJ_PROFILE NAMESPACE_ZOT . '/activity/profile'
const GRAVITY_PARENT 0
const GRAVITY_LIKE 3
const GRAVITY_COMMENT 6
const ACCOUNT_OK 0x0000
const ACCOUNT_UNVERIFIED 0x0001
const ACCOUNT_BLOCKED 0x0002
const ACCOUNT_EXPIRED 0x0004
const ACCOUNT_REMOVED 0x0008
const ACCOUNT_PENDING 0x0010
const ACCOUNT_ROLE_ADMIN 0x1000
const ITEM_VISIBLE 0x0000
const ITEM_HIDDEN 0x0001
const ITEM_BLOCKED 0x0002
const ITEM_MODERATED 0x0004
const ITEM_SPAM 0x0008
const ITEM_DELETED 0x0010
const ITEM_UNPUBLISHED 0x0020
const ITEM_WEBPAGE 0x0040
const ITEM_ORIGIN 0x0001
const ITEM_UNSEEN 0x0002
const ITEM_STARRED 0x0004
const ITEM_UPLINK 0x0008
const ITEM_UPLINK_PRV 0x0010
const ITEM_WALL 0x0020
const ITEM_THREAD_TOP 0x0040
const ITEM_NOTSHOWN 0x0080
const ITEM_NSFW 0x0100
const ITEM_RELAY 0x0200
const ITEM_MENTIONSME 0x0400
Function Documentation
absurl ($path)
appdirpath ()
Referenced by get_capath().
argc ()
Referenced by App\__construct(), _well_known_init(), admin_content(), admin_page_dbsync(), admin_page_users(), admin_post(), allfriends_content(), api_get_user(), attach_init(), channel_content(), channel_init(), common_init(), connections_content(), connections_init(), contactgroup_content(), display_content(), editpost_content(), events_content(), feed_init(), group_content(), group_post(), like_content(), lockview_content(), manage_content(), message_content(), new_channel_init(), notify_init(), oembed_init(), oexchange_content(), oexchange_init(), page_content(), photo_init(), photos_content(), photos_init(), photos_post(), ping_init(), poco_init(), poller_run(), post_init(), profile_init(), profile_photo_post(), profiles_aside(), profiles_content(), profiles_init(), profiles_post(), queue_run(), register_init(), regmod_content(), settings_aside(), settings_post(), setup_init(), share_init(), starred_init(), subthread_content(), tagger_content(), uexport_init(), update_channel_content(), update_display_content(), update_network_content(), update_search_content(), viewconnections_init(), viewsrc_content(), wall_attach_post(), wall_upload_post(), and zotfeed_init().
argv ($x)
Referenced by App\__construct(), _well_known_init(), admin_content(), admin_page_dbsync(), admin_page_users(), admin_post(), allfriends_content(), api_get_user(), api_statuses_destroy(), api_statuses_repeat(), api_statuses_show(), attach_init(), channel_content(), channel_init(), common_init(), connections_content(), connections_init(), connections_post(), contactgroup_content(), display_content(), editpost_content(), events_content(), feed_init(), group_content(), group_post(), like_content(), lockview_content(), manage_content(), message_aside(), message_content(), new_channel_init(), notify_init(), oembed_init(), oexchange_content(), oexchange_init(), page_content(), photo_init(), photos_content(), photos_init(), photos_post(), ping_init(), poco_init(), poller_run(), post_init(), profile_init(), profile_photo_post(), profile_tabs(), profiles_aside(), profiles_content(), profiles_init(), profiles_post(), queue_run(), register_init(), regmod_content(), settings_aside(), settings_post(), setup_init(), share_init(), starred_init(), subthread_content(), tagger_content(), uexport_init(), update_channel_content(), update_display_content(), update_network_content(), update_search_content(), view_init(), viewconnections_init(), viewsrc_content(), wall_attach_post(), wall_upload_post(), and zotfeed_init().
build_querystring ($params, $name = null)
returns querystring as string from a mapped array
Parameters
params Array
Returns
string
Referenced by network_init().
check_config (& $a)
Synchronise plugins:
$a->config['system']['addon'] contains a comma-separated list of names of plugins/addons which are used on this system. Go through the database list of already installed addons, and if we have an entry, but it isn't in the config list, call the unload procedure and mark it uninstalled in the database (for now we'll remove it). Then go through the config list and if we have a plugin that isn't installed, call the install procedure and add it to the database.
clean_urls ()
Referenced by z_path().
construct_page (& $a)
Build the page - now that we have all the components
curPageURL ()
Returns the complete URL of the current page, e.g.: http(s)://something.com/network
Taken from http://webcheatsheet.com/php/get_current_page_url.php
Referenced by construct_page().
current_theme ()
Referenced by FriendicaSmarty\__construct(), construct_page(), current_theme_url(), and theme_include().
current_theme_url ()
Return full URL to theme which is currently in effect. Provide a sane default if nothing is chosen or the specified theme does not exist.
Referenced by construct_page().
dba_timer ()
Referenced by Item\get_template_data(), network_content(), ping_init(), and Template\replace_macros().
fix_system_urls ($oldurl, $newurl)
Referenced by check_config().
get_account_id ()
Referenced by api_user(), change_channel(), channel_content(), events_post(), feed_init(), import_post(), manage_content(), mood_init(), nav(), new_channel_content(), new_channel_post(), new_contact(), profile_content(), profile_photo_post(), profiles_init(), settings_post(), and zotfeed_init().
get_app ()
Referenced by FriendicaSmarty\__construct(), FriendicaSmartyEngine\__construct(), allowed_public_recips(), api_apply_template(), api_format_items(), api_get_user(), api_statuses_home_timeline(), api_statuses_repeat(), api_user(), argc(), argv(), atom_entry(), authenticate_success(), avatar_img(), bbcode(), best_link_url(), call_hooks(), categories_widget(), change_channel(), channel_remove(), check_form_security_token(), check_form_security_token_ForbiddenOnErr(), check_form_security_token_redirectOnErr(), check_htaccess(), common_friends_visitor_widget(), connections_content(), consume_feed(), contact_block(), contact_select(), create_identity(), current_theme(), deliver_run(), dfrn_deliver(), drop_item(), event_store(), fetch_url(), fileas_widget(), findpeople_widget(), fix_attached_photo_permissions(), fix_private_photos(), format_event_diaspora(), get_account_id(), get_best_language(), get_birthdays(), get_events(), get_form_security_token(), get_markup_template(), get_observer_hash(), get_plink(), get_theme_config_file(), get_theme_screenshot(), gprobe_run(), group_select(), guess_image_type(), head_add_css(), head_add_js(), head_get_css(), head_get_js(), import_channel_photo(), import_post(), import_profile_photo(), info(), is_site_admin(), item_message_id(), item_permissions_sql(), load_contact_links(), load_hooks(), local_delivery(), login(), FKOAuth1\loginUser(), lrdd(), manage_content(), map_scope(), nav_set_selected(), new_contact(), new_follower(), notice(), notification(), notifier_run(), oembed_fetch_url(), oembed_format_object(), oembed_iframe(), onepoll_run(), permissions_sql(), ping_init(), poco_load(), poller_run(), post_activity_item(), post_url(), preg_heart(), prepare_body(), proc_run(), profile_activity(), profile_sidebar(), public_permissions_sql(), replace_macros(), rmagic_init(), saved_searches(), scale_external_images(), search(), send_message(), send_reg_approval_email(), send_status_notifications(), send_verification_email(), smilies(), tag_deliver(), terminate_friendship(), tgroup_check(), theme_include(), tt(), update_suggestions(), user_allow(), what_next(), z_fetch_url(), and zot_finger().
get_birthdays ()
get_events ()
get_max_import_size ()
Referenced by limit_body_size().
get_my_address ()
Referenced by rmagic_init(), zid(), and zid_init().
get_my_url ()
Referenced by nav(), and zid().
get_observer_hash ()
Referenced by attach_by_hash(), attach_by_hash_nodata(), attach_store(), common_content(), common_friends_visitor_widget(), display_content(), editpost_content(), new_contact(), photo_init(), photos_post(), prepare_body(), suggest_content(), viewconnections_content(), wall_attach_post(), and z_readdir().
goaway ($s)
Referenced by admin_page_dbsync(), admin_page_logs_post(), admin_page_plugins(), admin_page_site_post(), admin_page_themes(), admin_page_users(), admin_page_users_post(), admin_post(), api_content(), authenticate_success(), channel_remove(), check_form_security_token_redirectOnErr(), connections_content(), connections_post(), delegate_content(), directory_content(), drop_item(), events_post(), filerm_content(), follow_init(), group_content(), group_post(), intro_post(), item_post(), login_content(), lostpass_content(), lostpass_post(), magic_init(), manage_content(), message_content(), mood_init(), network_content(), new_channel_post(), notifications_post(), notify_init(), photos_post(), post_init(), profile_photo_post(), profiles_init(), randprof_init(), redir_init(), register_post(), removeme_content(), rmagic_init(), rmagic_post(), search_content(), settings_post(), tagrm_content(), tagrm_post(), toggle_mobile_init(), and zid_init().
info ($s)
Referenced by admin_page_dbsync(), admin_page_logs_post(), admin_page_plugins(), admin_page_site_post(), admin_page_themes(), admin_post(), authenticate_success(), community_content(), connections_content(), connections_post(), crepair_post(), directory_content(), dirfind_content(), file_tag_save_file(), follow_init(), fsuggest_post(), group_content(), group_post(), intro_post(), item_post(), lostpass_content(), lostpass_post(), match_content(), message_content(), network_content(), notifications_content(), oexchange_content(), post_init(), profile_photo_post(), profiles_init(), profiles_post(), register_post(), regmod_content(), settings_post(), suggest_content(), tagrm_post(), user_allow(), and viewconnections_content().
is_ajax ()
Referenced by admin_content(), admin_post(), photos_post(), and viewsrc_content().
is_site_admin ()
Referenced by admin_content(), admin_post(), check_account_admin(), findpeople_widget(), invite_content(), invite_post(), nav(), ping_init(), register_post(), and regmod_content().
killme ()
Referenced by FriendicaSmartyEngine\__construct(), acl_init(), admin_content(), api_content(), api_ff_ids(), api_friendica_version(), api_oauth_access_token(), api_oauth_request_token(), api_statusnet_version(), attach_init(), check_form_security_token_ForbiddenOnErr(), contactgroup_content(), events_content(), fbrowser_content(), feed_init(), filer_content(), filerm_content(), get_feed_for(), goaway(), http_status_exit(), item_post(), json_return_and_die(), like_content(), lockview_content(), msearch_post(), network_content(), oembed_init(), oexchange_init(), opensearch_init(), parse_url_content(), photo_init(), photos_post(), ping_init(), poco_init(), poller_run(), post_init(), pretheme_init(), qsearch_init(), App\register_template_engine(), regmod_content(), search_ac_init(), setup_init(), share_init(), siteinfo_init(), starred_init(), subthread_content(), system_unavailable(), tagger_content(), App\template_engine(), uexport_init(), update_channel_content(), update_community_content(), update_display_content(), update_network_content(), update_search_content(), view_init(), viewsrc_content(), wall_attach_post(), wall_upload_post(), wfinger_init(), xml_status(), and xrd_init().
load_contact_links ($uid)
Referenced by api_call().
local_user ()
Referenced by Item\__construct(), acl_init(), allfriends_content(), api_content(), api_get_user(), api_post(), api_user(), best_link_url(), App\build_pagehead(), change_channel(), channel_content(), channel_init(), channel_remove(), chanview_content(), common_friends_visitor_widget(), community_content(), community_init(), connections_content(), connections_init(), connections_post(), contact_select(), contactgroup_content(), crepair_content(), crepair_init(), crepair_post(), delegate_content(), directory_aside(), directory_content(), display_content(), drop_item(), drop_items(), editpost_content(), events_content(), events_post(), fbrowser_content(), fileas_widget(), filer_content(), filerm_content(), findpeople_widget(), follow_content(), follow_init(), fsuggest_content(), fsuggest_post(), get_birthdays(), Item\get_comment_box(), get_events(), Item\get_template_data(), group_aside(), group_content(), group_get_members(), group_post(), group_select(), group_side(), hcard_init(), intro_content(), intro_post(), invite_content(), invite_post(), item_content(), item_permissions_sql(), item_post(), lockview_content(), login(), login_content(), magic_init(), manage_content(), match_content(), message_content(), message_post(), mood_content(), mood_init(), nav(), network_content(), network_init(), new_contact(), nogroup_content(), nogroup_init(), notifications_content(), notifications_post(), notify_content(), notify_init(), oexchange_content(), permissions_sql(), photos_content(), photos_init(), photos_post(), ping_init(), poco_init(), poke_content(), poke_init(), post_init(), prepare_body(), private_messages_list(), profile_activity(), profile_content(), profile_create_sidebar(), profile_init(), profile_photo_aside(), profile_photo_init(), profile_photo_post(), profile_sidebar(), profiles_aside(), profiles_content(), profiles_init(), profiles_post(), profperm_aside(), profperm_content(), profperm_init(), qsearch_init(), redbasic_form(), redir_init(), regmod_content(), removeme_content(), removeme_post(), rmagic_init(), saved_searches(), search_ac_init(), search_content(), search_init(), search_saved_searches(), service_class_allows(), service_class_fetch(), Conversation\set_mode(), settings_aside(), settings_post(), share_init(), smilies(), starred_init(), stream_perms_api_uids(), subthread_content(), suggest_content(), suggest_init(), tagger_content(), tagrm_content(), tagrm_post(), theme_content(), theme_post(), uexport_init(), vcard_from_xchan(), viewconnections_aside(), viewconnections_content(), viewconnections_init(), viewsrc_content(), and zid_init().
login ($register = false, $form_id = 'main-login', $hiddens = false)
Referenced by admin_content(), api_content(), channel_content(), follow_content(), login_content(), network_content(), notify_content(), oexchange_content(), profile_content(), and regmod_content().
notice ($s)
Referenced by admin_content(), admin_page_plugins(), admin_page_themes(), admin_page_users(), admin_page_users_post(), allfriends_content(), api_content(), api_post(), apps_content(), attach_init(), channel_content(), channel_init(), chanview_content(), check_form_security_token_redirectOnErr(), common_content(), common_init(), community_content(), connections_content(), connections_post(), crepair_content(), crepair_post(), delegate_content(), directory_content(), display_content(), drop_item(), editpost_content(), events_content(), events_post(), follow_init(), fsuggest_content(), fsuggest_post(), group_add(), group_content(), group_post(), hcard_init(), import_post(), intro_content(), intro_post(), invite_content(), invite_post(), item_post(), like_content(), lostpass_content(), lostpass_post(), magic_init(), manage_content(), match_content(), message_content(), message_post(), mood_content(), network_content(), network_init(), new_channel_content(), new_channel_post(), nogroup_content(), notifications_content(), notifications_post(), page_content(), photos_content(), photos_post(), poke_content(), post_init(), profile_content(), profile_init(), profile_load(), profile_photo_post(), profiles_content(), profiles_init(), profiles_post(), profperm_content(), register_content(), register_post(), regmod_content(), rmagic_post(), search_content(), settings_post(), suggest_content(), user_deny(), viewconnections_content(), viewsrc_content(), wall_attach_post(), wall_upload_post(), and xchan_content().
proc_run ($cmd)
Wrap calls to proc_close(proc_open()) and call hook so plugins can take part in process :)
args: $cmd program to run next args are passed as $cmd command line
e.g.: proc_run("ls","-la","/tmp");
$cmd and string args are surrounded with ""
Referenced by connections_content(), connections_post(), create_identity(), drop_item(), drop_items(), events_post(), fsuggest_post(), item_expire(), item_post(), like_content(), local_delivery(), mood_init(), notifier_run(), photo_upload(), photos_post(), poller_run(), post_activity_item(), process_delivery(), profile_activity(), profile_photo_post(), profiles_post(), send_message(), settings_post(), tag_deliver(), tagger_content(), zid_init(), and zot_refresh().
profile_create_sidebar (& $a)
Referenced by channel_aside(), common_aside(), hcard_aside(), profile_aside(), profile_photo_aside(), profiles_aside(), profperm_aside(), and viewconnections_aside().
profile_load (& $a, $nickname, $profile = 0)
Function : profile_load App $a string $nickname int $profile
Summary: Loads a profile into the page sidebar. The function requires a writeable copy of the main App structure, and the nickname of a registered local account.
If the viewer is an authenticated remote viewer, the profile displayed is the one that has been configured for his/her viewing in the Contact manager. Passing a non-zero profile ID can also allow a preview of a selected profile by the owner.
Profile information is placed in the App structure for later retrieval. Honours the owner's chosen theme for display.
load/reload current theme info
Referenced by channel_init(), common_init(), hcard_init(), profile_init(), profile_photo_init(), profiles_init(), profperm_init(), and viewconnections_init().
profile_sidebar ($profile, $block = 0)
Function: profile_sidebar
Formats a profile for display in the sidebar. It is very difficult to templatise the HTML completely because of all the conditional logic.
: array $profile
Returns HTML string stuitable for sidebar inclusion Exceptions: Returns empty string if passed $profile is wrong type or not populated
Referenced by profile_create_sidebar().
profile_tabs ($a, $is_owner = False, $nickname = Null)
Referenced by channel_content(), events_content(), photos_content(), and profile_content().
remote_user ()
Referenced by channel_content(), community_content(), directory_content(), display_content(), drop_items(), hcard_init(), item_content(), item_permissions_sql(), item_post(), nav(), permissions_sql(), photos_content(), photos_init(), photos_post(), poco_init(), post_init(), profile_content(), profile_create_sidebar(), profile_sidebar(), redir_init(), search_content(), subthread_content(), tagger_content(), viewconnections_aside(), viewconnections_content(), viewconnections_init(), zid_init(), and zotfeed_init().
startup ()
Reverse the effect of magic_quotes_gpc if it is enabled. Please disable magic_quotes_gpc so we don't have to do this. See http://php.net/manual/en/security.magicquotes.disabling.php
Referenced by App\__construct().
system_unavailable ()
x ($s, $k = NULL)
Referenced by FriendicaSmarty\__construct(), App\__construct(), acl_init(), admin_page_logs_post(), admin_page_plugins(), admin_page_site(), admin_page_site_post(), admin_page_themes(), admin_page_users_post(), api_content(), api_direct_messages_box(), api_direct_messages_new(), api_favorites(), api_format_messages(), api_get_user(), api_login(), api_post(), api_statuses_f(), api_statuses_home_timeline(), api_statuses_mentions(), api_statuses_public_timeline(), api_statuses_show(), api_statuses_update(), api_statuses_user_timeline(), api_user(), attach_store(), authenticate_success(), bbcode(), bbtoevent(), best_link_url(), App\build_pagehead(), channel_aside(), channel_content(), check_config(), check_form_security_token(), community_content(), connections_aside(), connections_content(), connections_post(), construct_page(), consume_feed(), create_account(), create_identity(), crepair_init(), crepair_post(), current_theme(), del_config(), del_pconfig(), del_xconfig(), delegate_content(), detect_language(), directory_content(), dirfind_init(), dirsearch_content(), encode_rel_links(), events_content(), events_post(), feed_init(), filerm_content(), get_atom_elements(), App\get_baseurl(), get_browser_language(), get_item_elements(), get_max_import_size(), get_my_address(), get_my_url(), get_plink(), get_public_feed(), Item\get_template_data(), group_add(), group_rmv(), hcard_init(), import_post(), import_xchan(), info(), intro_content(), invite_post(), item_post(), item_store(), item_store_update(), lang_selector(), load_contact_links(), local_delivery(), local_user(), lostpass_content(), lrdd(), magic_init(), mail_store(), message_content(), message_post(), mood_content(), mood_init(), nav(), navbar_complete(), network_content(), network_init(), network_query_get_sel_tab(), new_channel_content(), nogroup_init(), notice(), notifications_content(), oexchange_content(), parse_url_content(), photo_upload(), photos_content(), photos_post(), ping_init(), poco_init(), poco_load(), poke_content(), poke_init(), post_activity_item(), printable(), probe_content(), proc_run(), process_delivery(), profile_photo_post(), profile_sidebar(), profile_tabs(), profiles_post(), qsearch_init(), redir_init(), ref_session_read(), register_content(), register_post(), App\register_template_engine(), regmod_content(), remote_user(), removeme_post(), saved_searches(), search_ac_init(), search_content(), search_init(), search_post(), service_class_allows(), service_class_fetch(), App\set_baseurl(), settings_post(), setup_content(), setup_init(), siteinfo_init(), suggest_init(), t(), tagrm_post(), App\template_engine(), tt(), validate_channelname(), wall_upload_post(), webfinger_content(), wfinger_init(), xchan_content(), z_fetch_url(), z_post_url(), and zfinger_init().
z_birthday ($dob, $tz, $format = "Y-m-d H:i:s")
Referenced by zfinger_init().
z_path ()
Referenced by absurl(), and hostxrd_init().
z_root ()
Referenced by allowed_public_recips(), chanlink_cid(), chanlink_hash(), chanlink_url(), channel_content(), chanview_content(), check_config(), connections_content(), create_identity(), deliver_run(), directory_content(), display_content(), event_store(), follow_init(), format_css_if_exists(), format_js_if_exists(), group_post(), hostxrd_init(), import_post(), import_xchan(), intro_post(), item_store(), like_content(), login_content(), lostpass_content(), lostpass_post(), magic_init(), magiclink_url(), manage_content(), mood_init(), navbar_complete(), network_content(), new_channel_post(), notifications_post(), notifier_run(), photo_upload(), photos_album_widget(), photos_create_item(), post_init(), profile_activity(), public_recips(), redir_init(), register_post(), removeme_content(), rmagic_init(), rmagic_post(), search_content(), send_reg_approval_email(), send_verification_email(), setup_content(), siteinfo_content(), siteinfo_init(), sync_directories(), user_allow(), vcard_from_xchan(), wfinger_init(), zfinger_init(), zid_init(), zot_build_packet(), zot_fetch(), and zot_new_uid().
zid ($s, $force = false)
zid($s,$force = false) Adds a zid parameter to a url
Parameters
string $s The url to accept the zid
boolean $force Currently unused
Returns
string
'zid' string url - url to accept zid string zid - urlencoded zid string result - the return string we calculated, change it if you want to return something else
Referenced by bb_ShareAttributes(), dirfind_content(), intro_content(), localize_item(), match_content(), notifications_content(), and viewconnections_content().
zid_init (& $a)
zid_init(&$a) If somebody arrives at our site using a zid, add their xchan to our DB if we don't have it already. And if they aren't already authenticated here, attempt reverse magic auth.
'zid_init' string 'zid' - their zid string 'url' - the destination url
Variable Documentation
const ABOOK_FLAG_ARCHIVED 0x0008
Referenced by connections_content(), and poller_run().
const ABOOK_FLAG_BLOCKED 0x0001
Referenced by acl_init(), channel_content(), connections_content(), get_all_perms(), group_content(), group_get_members(), intro_post(), network_content(), perm_is_allowed(), and search_content().
const ABOOK_FLAG_HIDDEN 0x0004
Referenced by connections_content(), intro_content(), intro_post(), onepoll_run(), and poller_run().
const ABOOK_FLAG_IGNORED 0x0002
Referenced by connections_content(), get_all_perms(), intro_post(), and perm_is_allowed().
const ABOOK_FLAG_PENDING 0x0010
Referenced by acl_init(), collect_recipients(), connections_content(), connections_post(), group_content(), group_get_members(), intro_content(), ping_init(), and zot_refresh().
const ABOOK_FLAG_SELF 0x0080
Referenced by abook_connections(), abook_self(), acl_init(), api_get_user(), collect_recipients(), connections_content(), connections_post(), contact_remove(), contact_select(), contactgroup_content(), create_identity(), get_all_perms(), group_content(), group_get_members(), intro_content(), load_contact_links(), new_contact(), notifier_run(), perm_is_allowed(), ping_init(), poco_init(), settings_aside(), and zot_refresh().
const ACCOUNT_BLOCKED 0x0002
Referenced by admin_page_users(), admin_page_users_post(), register_post(), and user_allow().
const ACCOUNT_EXPIRED 0x0004
Referenced by poller_run().
const ACCOUNT_OK 0x0000
Account Flags
Referenced by account_verify_password(), create_account(), onepoll_run(), and poller_run().
const ACCOUNT_PENDING 0x0010
Referenced by admin_page_users(), ping_init(), register_post(), and user_allow().
const ACCOUNT_REMOVED 0x0008
const ACCOUNT_ROLE_ADMIN 0x1000
Account roles
Referenced by create_account(), is_site_admin(), and send_reg_approval_email().
const ACCOUNT_UNVERIFIED 0x0001
Referenced by account_verify_password(), onepoll_run(), poller_run(), and register_post().
const ACTIVITY_DISLIKE NAMESPACE_ZOT . '/activity/dislike'
Referenced by Item\add_child(), Conversation\add_thread(), consume_feed(), like_content(), local_delivery(), localize_item(), notifications_content(), and visible_activity().
const ACTIVITY_FAVORITE NAMESPACE_ACTIVITY_SCHEMA . 'favorite'
const ACTIVITY_FOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'follow'
Referenced by consume_feed(), and subthread_content().
const ACTIVITY_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'make-friend'
Referenced by localize_item(), and notifications_content().
const ACTIVITY_JOIN NAMESPACE_ACTIVITY_SCHEMA . 'join'
const ACTIVITY_LIKE NAMESPACE_ACTIVITY_SCHEMA . 'like'
activity stream defines
Referenced by Item\add_child(), Conversation\add_thread(), consume_feed(), like_content(), local_delivery(), localize_item(), notifications_content(), and visible_activity().
const ACTIVITY_MOOD NAMESPACE_ZOT . '/activity/mood'
Referenced by localize_item(), and mood_init().
const ACTIVITY_OBJ_ALBUM NAMESPACE_ACTIVITY_SCHEMA . 'photo-album'
const ACTIVITY_OBJ_COMMENT NAMESPACE_ACTIVITY_SCHEMA . 'comment'
const ACTIVITY_OBJ_EVENT NAMESPACE_ACTIVITY_SCHEMA . 'event'
Referenced by consume_feed(), event_store(), local_delivery(), localize_item(), and process_delivery().
const ACTIVITY_OBJ_GROUP NAMESPACE_ACTIVITY_SCHEMA . 'group'
const ACTIVITY_OBJ_HEART NAMESPACE_ZOT . '/activity/heart'
const ACTIVITY_OBJ_NOTE NAMESPACE_ACTIVITY_SCHEMA . 'note'
Referenced by api_format_items(), consume_feed(), like_content(), local_delivery(), localize_item(), post_activity_item(), subthread_content(), and tagger_content().
const ACTIVITY_OBJ_P_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'profile-photo'
const ACTIVITY_OBJ_PERSON NAMESPACE_ACTIVITY_SCHEMA . 'person'
Referenced by get_atom_elements(), local_delivery(), localize_item(), photos_post(), and poke_init().
const ACTIVITY_OBJ_PHOTO NAMESPACE_ACTIVITY_SCHEMA . 'photo'
Referenced by like_content(), localize_item(), photos_post(), subthread_content(), and tagger_content().
const ACTIVITY_OBJ_PROFILE NAMESPACE_ZOT . '/activity/profile'
Referenced by profile_activity().
const ACTIVITY_OBJ_TAGTERM NAMESPACE_ZOT . '/activity/tagterm'
Referenced by consume_feed(), local_delivery(), and tagger_content().
const ACTIVITY_POKE NAMESPACE_ZOT . '/activity/poke'
Referenced by local_delivery(), localize_item(), and poke_init().
const ACTIVITY_POST NAMESPACE_ACTIVITY_SCHEMA . 'post'
Referenced by api_format_items(), api_status_show(), api_users_show(), construct_verb(), event_store(), item_post(), item_post_type(), local_delivery(), mail_store(), post_activity_item(), and send_status_notifications().
const ACTIVITY_REQ_FRIEND NAMESPACE_ACTIVITY_SCHEMA . 'request-friend'
Referenced by consume_feed(), and local_delivery().
const ACTIVITY_TAG NAMESPACE_ACTIVITY_SCHEMA . 'tag'
Referenced by consume_feed(), local_delivery(), photos_post(), tag_deliver(), and tagger_content().
const ACTIVITY_UNFOLLOW NAMESPACE_ACTIVITY_SCHEMA . 'stop-following'
Referenced by consume_feed(), and get_atom_elements().
const ACTIVITY_UNFRIEND NAMESPACE_ACTIVITY_SCHEMA . 'remove-friend'
Referenced by consume_feed().
const ACTIVITY_UPDATE NAMESPACE_ACTIVITY_SCHEMA . 'update'
Referenced by profile_activity().
const ATOM_TIME 'Y-m-d\TH:i:s\Z'
Referenced by api_account_rate_limit_status(), api_rss_extra(), atom_entry(), format_event_html(), and get_feed_for().
const ATTACH_FLAG_DIR 0x0001
Referenced by z_readdir().
const ATTACH_FLAG_OS 0x0002
Referenced by attach_init().
const CONTACT_IS_FOLLOWER 1
relationship types
Referenced by consume_feed(), local_delivery(), lose_sharer(), and new_follower().
const CONTACT_IS_FRIEND 3
Referenced by lose_follower(), lose_sharer(), and new_follower().
const CONTACT_IS_SHARING 2
Referenced by dfrn_deliver(), lose_follower(), and new_follower().
const DB_UPDATE_VERSION 1042
Referenced by api_statusnet_config(), check_config(), and identity_basic_export().
const DEFAULT_DB_ENGINE 'MyISAM'
Not yet used
const DIRECTORY_FALLBACK_MASTER 'https://zothub.com'
Referenced by directory_content(), directory_run(), navbar_complete(), and sync_directories().
const DIRECTORY_MODE_NORMAL 0x0000
Referenced by directory_run(), dirsearch_content(), import_xchan(), sync_directories(), and zfinger_init().
const DIRECTORY_MODE_PRIMARY 0x0001
Referenced by directory_content(), directory_run(), navbar_complete(), poller_run(), sync_directories(), and zfinger_init().
const DIRECTORY_MODE_SECONDARY 0x0002
Referenced by poller_run(), and zfinger_init().
const DIRECTORY_MODE_STANDALONE 0x0100
Referenced by directory_content(), directory_run(), import_xchan(), navbar_complete(), sync_directories(), and zfinger_init().
const DIRECTORY_REALM 'RED_GLOBAL'
const EOL '<br />' . "\r\n"
Referenced by admin_page_dbsync(), admin_page_site_post(), admin_page_users(), allfriends_content(), api_content(), api_post(), apps_content(), attach_init(), authenticate_success(), channel_content(), channel_init(), chanview_content(), check_account_email(), check_account_invite(), check_form_security_std_err_msg(), check_keys(), check_php(), common_content(), common_init(), community_content(), connections_content(), connections_post(), crepair_content(), crepair_post(), delegate_content(), directory_content(), dirfind_content(), display_content(), drop_item(), editpost_content(), events_content(), events_post(), follow_init(), fsuggest_content(), fsuggest_post(), group_add(), group_content(), group_post(), hcard_init(), import_post(), import_xchan(), intro_content(), intro_post(), invite_content(), invite_post(), item_post(), like_content(), load_database(), lostpass_content(), lostpass_post(), magic_init(), manage_content(), match_content(), message_content(), message_post(), mood_content(), network_content(), network_init(), new_channel_content(), new_channel_post(), nogroup_content(), notifications_content(), notifications_post(), oexchange_content(), page_content(), photos_content(), photos_post(), poke_content(), post_init(), profile_content(), profile_init(), profile_load(), profile_photo_post(), profiles_content(), profiles_init(), profiles_post(), profperm_content(), register_content(), register_post(), regmod_content(), search_content(), settings_post(), setup_content(), suggest_content(), tagrm_post(), user_allow(), user_deny(), viewconnections_content(), viewsrc_content(), wall_attach_post(), wall_upload_post(), and xchan_content().
const GRAVITY_COMMENT 6
Referenced by tagger_content().
const GRAVITY_LIKE 3
Referenced by consume_feed(), local_delivery(), and subthread_content().
const GRAVITY_PARENT 0
item weight for query ordering
const HUBLOC_FLAGS_PRIMARY 0x0001
Referenced by create_identity(), import_author_xchan(), import_post(), import_xchan(), magic_init(), xchan_mail_query(), xchan_query(), zfinger_init(), zot_finger(), zot_get_hubloc(), and zot_refresh().
const HUBLOC_FLAGS_UNVERIFIED 0x0002
Referenced by zfinger_init().
const ITEM_BLOCKED 0x0002
const ITEM_DELETED 0x0010
Referenced by delete_item_lowlevel(), encode_item(), expire_run(), get_item_elements(), item_store(), like_content(), notifier_run(), and process_delivery().
const ITEM_HIDDEN 0x0001
Referenced by item_post(), photo_upload(), and photos_create_item().
const ITEM_MENTIONSME 0x0400
Referenced by network_content(), and tag_deliver().
const ITEM_MODERATED 0x0004
Referenced by item_post().
const ITEM_NOTSHOWN 0x0080
Referenced by like_content().
const ITEM_NSFW 0x0100
Referenced by encode_item_flags().
const ITEM_ORIGIN 0x0001
Item Flags
Referenced by event_store(), item_post(), like_content(), mood_init(), notifier_run(), photo_upload(), photos_create_item(), poke_init(), post_activity_item(), profile_activity(), and tag_deliver().
const ITEM_RELAY 0x0200
const ITEM_SPAM 0x0008
const ITEM_STARRED 0x0004
Referenced by api_format_items(), api_get_user(), Item\get_template_data(), network_content(), and starred_init().
const ITEM_THREAD_TOP 0x0040
Referenced by channel_content(), encode_item_flags(), event_store(), format_notification(), item_post(), item_store(), mood_init(), network_content(), photo_upload(), photos_create_item(), poke_init(), post_activity_item(), profile_activity(), and tag_deliver().
const ITEM_UNPUBLISHED 0x0020
const ITEM_UNSEEN 0x0002
Referenced by api_statuses_home_timeline(), channel_content(), display_content(), format_notification(), item_post(), item_store(), mood_init(), network_content(), and ping_init().
const ITEM_UPLINK 0x0008
Referenced by item_store(), notifier_run(), and tag_deliver().
const ITEM_UPLINK_PRV 0x0010
const ITEM_VISIBLE 0x0000
Item visibility
Referenced by first_post_date(), item_post(), photo_upload(), photos_create_item(), and ping_init().
const ITEM_WALL 0x0020
Referenced by api_get_user(), channel_content(), drop_item(), event_store(), events_content(), first_post_date(), item_post(), item_store(), like_content(), mood_init(), notification(), notifier_run(), photo_upload(), photos_create_item(), ping_init(), poke_init(), post_activity_item(), profile_activity(), tag_deliver(), and zot_feed().
const ITEM_WEBPAGE 0x0040
Referenced by item_post(), and page_content().
const JPEG_QUALITY 100
Image storage quality. Lower numbers save space at cost of image detail. For ease of upgrade, please do not change here. Change jpeg quality with $a->config['system']['jpeg_quality'] = n; in .htconfig.php, where n is netween 1 and 100, and with very poor results below about 50
Referenced by photo_gd\imageString(), and photo_imagick\load().
const LANGUAGE_DETECT_MIN_CONFIDENCE 0.01
Referenced by detect_language().
const LANGUAGE_DETECT_MIN_LENGTH 128
Language detection parameters
Referenced by detect_language().
const LOGGER_ALL 4
Referenced by admin_page_logs().
const LOGGER_DATA 3
Referenced by admin_page_logs(), check_form_security_token_ForbiddenOnErr(), check_form_security_token_redirectOnErr(), consume_feed(), detect_language(), dfrn_deliver(), directory_content(), fetch_xrd_links(), fix_private_photos(), import_xchan(), item_post(), item_store(), item_store_update(), lrdd(), mail_store(), message_content(), message_post(), mini_group_select(), new_contact(), notifier_run(), parse_xml_string(), photos_post(), poco_load(), post_post(), tag_deliver(), webfinger_dfrn(), xml2array(), zot_build_packet(), zot_fetch(), zot_import(), zot_process_response(), zot_refresh(), and zot_register_hub().
const LOGGER_DEBUG 2
Referenced by Item\add_child(), Conversation\add_thread(), admin_page_logs(), api_login(), api_statuses_user_timeline(), authenticate_success(), avatar_img(), consume_feed(), delete_imported_item(), deliver_run(), dfrn_deliver(), directory_content(), directory_run(), expire_run(), fix_private_photos(), Conversation\get_template_data(), group_content(), guess_image_type(), import_author_xchan(), import_channel_photo(), import_directory_profile(), import_profile_photo(), import_xchan(), item_post(), item_store(), item_store_update(), like_content(), limit_body_size(), local_delivery(), FKOAuth1\loginUser(), lrdd(), mail_store(), mood_init(), notification(), notifier_run(), parse_url_content(), photo_upload(), photos_post(), poco_init(), poco_load(), poke_init(), post_post(), process_delivery(), process_profile_delivery(), profile_load(), redir_init(), Item\remove_child(), scale_external_images(), enotify\send(), Conversation\set_mode(), syncdirs(), unload_plugin(), zot_finger(), zot_gethub(), and zot_register_hub().
const LOGGER_NORMAL 0
log levels
Referenced by admin_page_logs().
const LOGGER_TRACE 1
Referenced by admin_page_logs().
const MAIL_DELETED 0x0001
Referenced by ping_init().
const MAIL_ISREPLY 0x0004
const MAIL_RECALLED 0x0010
Referenced by encode_mail(), get_mail_elements(), and process_mail_delivery().
const MAIL_REPLIED 0x0002
const MAIL_SEEN 0x0008
Referenced by ping_init(), private_messages_fetch_conversation(), private_messages_fetch_message(), and private_messages_list().
const MAX_IMAGE_LENGTH -1
An alternate way of limiting picture upload sizes. Specify the maximum pixel length that pictures are allowed to be (for non-square pictures, it will apply to the longest side). Pictures longer than this length will be resized to be this length (on the longest side, the other side will be scaled appropriately). Modify this value using
$a->config['system']['max_image_length'] = n;
in .htconfig.php
If you don't want to set a maximum length, set to -1. The default value is defined by 'MAX_IMAGE_LENGTH' below.
Referenced by photo_upload().
const MAX_LIKERS 75
Maximum number of "people who like (or don't like) this" that we will list by name
const NAMESPACE_ACTIVITY 'http://activitystrea.ms/spec/1.0/'
Referenced by get_atom_elements(), and new_follower().
const NAMESPACE_ACTIVITY_SCHEMA 'http://activitystrea.ms/schema/1.0/'
Referenced by activity_match().
const NAMESPACE_ATOM1 'http://www.w3.org/2005/Atom'
const NAMESPACE_DFRN 'http://purl.org/macgirvin/dfrn/1.0'
Referenced by consume_feed(), get_atom_elements(), local_delivery(), and webfinger_dfrn().
const NAMESPACE_FEED 'http://schemas.google.com/g/2010#updates-from'
const NAMESPACE_GEORSS 'http://www.georss.org/georss'
Referenced by get_atom_elements().
const NAMESPACE_MEDIA 'http://purl.org/syndication/atommedia'
Referenced by encode_rel_links().
const NAMESPACE_OSTATUS 'http://ostatus.org/schema/1.0'
const NAMESPACE_OSTATUSSUB 'http://ostatus.org/schema/1.0/subscribe'
Referenced by webfinger_dfrn().
const NAMESPACE_POCO 'http://portablecontacts.net/spec/1.0'
Referenced by new_follower().
const NAMESPACE_SALMON_ME 'http://salmon-protocol.org/ns/magic-env'
const NAMESPACE_STATUSNET 'http://status.net/schema/api/1/'
Referenced by get_atom_elements().
const NAMESPACE_THREAD 'http://purl.org/syndication/thread/1.0'
Referenced by consume_feed(), and local_delivery().
const NAMESPACE_TOMB 'http://purl.org/atompub/tombstones/1.0'
Referenced by consume_feed(), and local_delivery().
const NAMESPACE_ZOT 'http://purl.org/zot'
various namespaces we may need to parse
const NETWORK_DFRN 'dfrn'
Network and protocol family types
Referenced by acl_init(), best_link_url(), consume_feed(), delegate_content(), get_birthdays(), network_to_name(), notifications_content(), redir_init(), and terminate_friendship().
const NETWORK_DIASPORA 'dspr'
Referenced by acl_init(), network_to_name(), and notifications_content().
const NETWORK_FACEBOOK 'face'
Referenced by network_to_name().
const NETWORK_FEED 'feed'
Referenced by network_to_name().
const NETWORK_GPLUS 'goog'
const NETWORK_LINKEDIN 'lnkd'
Referenced by network_to_name().
const NETWORK_MAIL 'mail'
Referenced by get_feed_for(), and network_to_name().
const NETWORK_MAIL2 'mai2'
const NETWORK_MYSPACE 'mysp'
Referenced by network_to_name().
const NETWORK_OSTATUS 'stat'
Referenced by network_to_name(), new_follower(), and notifications_content().
const NETWORK_PHANTOM 'unkn'
const NETWORK_XMPP 'xmpp'
Referenced by network_to_name().
const NETWORK_ZOT 'zot!'
Referenced by acl_init(), network_to_name(), and new_follower().
const NOTIFY_COMMENT 0x0008
Referenced by item_post(), local_delivery(), notification(), and send_status_notifications().
const NOTIFY_CONFIRM 0x0002
Referenced by notification().
const NOTIFY_INTRO 0x0001
email notification options
Referenced by new_follower(), and notification().
const NOTIFY_MAIL 0x0010
Referenced by local_delivery(), mail_store(), and notification().
const NOTIFY_POKE 0x0200
Referenced by local_delivery(), and notification().
const NOTIFY_PROFILE 0x0040
const NOTIFY_SUGGEST 0x0020
Referenced by local_delivery(), and notification().
const NOTIFY_SYSTEM 0x8000
Referenced by notification().
const NOTIFY_TAGSELF 0x0080
Referenced by notification(), and tag_deliver().
const NOTIFY_TAGSHARE 0x0100
Referenced by notification().
const NOTIFY_WALL 0x0004
Referenced by item_post(), and notification().
const PAGE_APPLICATION 0x0004
const PAGE_AUTOCONNECT 0x0002
const PAGE_DIRECTORY_CHANNEL 0x0008
Referenced by create_dir_account().
const PAGE_HIDDEN 0x0001
Referenced by create_dir_account(), and zfinger_init().
const PAGE_NORMAL 0x0000
page/profile types
PAGE_NORMAL is a typical personal profile account PAGE_SOAPBOX automatically approves all friend requests as CONTACT_IS_SHARING, (readonly) PAGE_COMMUNITY automatically approves all friend requests as CONTACT_IS_SHARING, but with write access to wall and comments (no email and not included in page owner's ACL lists) PAGE_FREELOVE automatically approves all friend requests as full friends (CONTACT_IS_FRIEND).
Referenced by create_identity(), and new_follower().
const PAGE_REMOVED 0x8000
Referenced by change_channel(), channel_remove(), channelx_by_hash(), channelx_by_n(), and channelx_by_nick().
const PERMS_A_DELEGATE 0x0800
Referenced by get_perms().
const PERMS_CONTACTS 0x0008
Referenced by get_all_perms(), map_scope(), perm_is_allowed(), and public_recips().
const PERMS_NETWORK 0x0002
Referenced by get_all_perms(), map_scope(), perm_is_allowed(), and public_recips().
const PERMS_PUBLIC 0x0001
Referenced by feed_init(), get_all_perms(), map_scope(), and perm_is_allowed().
const PERMS_R_ABOOK 0x0008
Referenced by get_perms().
const PERMS_R_PAGES 0x4000
Referenced by get_perms().
const PERMS_R_PHOTOS 0x0004
Referenced by get_perms().
const PERMS_R_PROFILE 0x0002
Referenced by get_perms().
const PERMS_R_STORAGE 0x1000
Referenced by get_perms().
const PERMS_R_STREAM 0x0001
Permissions
Referenced by get_perms().
const PERMS_SITE 0x0004
Referenced by get_all_perms(), map_scope(), perm_is_allowed(), and public_recips().
const PERMS_SPECIFIC 0x0080
Referenced by connections_content(), get_all_perms(), perm_is_allowed(), and public_recips().
const PERMS_W_CHAT 0x0400
Referenced by get_perms().
const PERMS_W_COMMENT 0x0080
Referenced by get_perms(), and public_recips().
const PERMS_W_MAIL 0x0100
Referenced by acl_init(), get_perms(), message_post(), and public_recips().
const PERMS_W_PAGES 0x8000
Referenced by get_perms().
const PERMS_W_PHOTOS 0x0200
Referenced by get_perms().
const PERMS_W_STORAGE 0x2000
Referenced by get_perms().
const PERMS_W_STREAM 0x0010
Referenced by api_ff_ids(), api_statuses_f(), get_perms(), and public_recips().
const PERMS_W_TAGWALL 0x0040
Referenced by get_perms().
const PERMS_W_WALL 0x0020
Referenced by get_perms().
const PNG_QUALITY 8
$a->config['system']['png_quality'] from 0 (uncompressed) to 9
Referenced by photo_gd\imageString(), and photo_imagick\load().
const RED_PLATFORM 'Red'
Red.
Red is an open source decentralised communications platform combined with a decentralised identity/authentication framework wrapped in an extensible content management system, providing website designers the ability to embed fully decentralised communications and social tools into many traditional website designs (blogs, forums, small business websites, charitable organisations, etc.). Red also provides DNS mobility and internet scale privacy/access control.
This allows any individual website to participate in a matrix of linked sites and people and media sharing which is far greater than the reach of an individual site.
If you are reading the source code and come across a function or code block which is not documented, but you have a good idea what it does, please add some descriptive comments and push it to the main project. Even if your description isn't perfect, it gives us a base which we can build on and correct - so that eventually everything is fully documented.
Referenced by api_statusnet_config(), App\build_pagehead(), identity_basic_export(), notification(), parse_url_content(), and siteinfo_init().
const RED_VERSION trim(file_get_contents('version.inc')) . 'R'
Referenced by admin_page_summary(), api_friendica_version(), api_statusnet_config(), App\build_pagehead(), get_feed_for(), identity_basic_export(), siteinfo_content(), and siteinfo_init().
const REGISTER_APPROVE 1
Referenced by admin_page_site(), ping_init(), and register_post().
const REGISTER_CLOSED 0
registration policies
Referenced by admin_page_site(), api_statusnet_config(), invite_content(), login_content(), register_content(), register_post(), and regmod_content().
const REGISTER_OPEN 2
Referenced by admin_page_site(), nav(), and register_post().
const SSL_POLICY_FULL 1
Referenced by admin_page_site(), dfrn_deliver(), fix_contact_ssl_policy(), and App\get_baseurl().
const SSL_POLICY_NONE 0
SSL redirection policies
Referenced by admin_page_site(), and dfrn_deliver().
const SSL_POLICY_SELFSIGN 2
Referenced by dfrn_deliver(), fix_contact_ssl_policy(), and App\get_baseurl().
const TERM_CATEGORY 3
Referenced by categories_widget(), decode_tags(), encode_item_terms(), file_tag_file_query(), filerm_content(), item_post(), and prepare_body().
const TERM_FILE 5
Referenced by decode_tags(), file_tag_file_query(), fileas_widget(), filer_content(), filerm_content(), network_content(), and prepare_body().
const TERM_HASHTAG 1
Referenced by decode_tags(), encode_item_terms(), format_term_for_display(), get_atom_elements(), handle_tag(), item_getfeedtags(), item_post(), network_content(), search_ac_init(), and search_content().
const TERM_MENTION 2
Referenced by decode_tags(), encode_item_terms(), fetch_post_tags(), format_term_for_display(), get_atom_elements(), get_mentions(), handle_tag(), item_getfeedtags(), item_post(), and tag_deliver().
const TERM_OBJ_PHOTO 2
const TERM_OBJ_POST 1
Referenced by delete_item_lowlevel(), fetch_post_tags(), filer_content(), get_atom_elements(), item_post(), item_store(), item_store_update(), search_content(), and tagadelic().
const TERM_PCATEGORY 4
Referenced by decode_tags().
const TERM_SAVEDSEARCH 6
Referenced by network_init(), saved_searches(), search_init(), and search_saved_searches().
const TERM_UNKNOWN 0
Tag/term types
Referenced by decode_tags(), encode_item_terms(), get_atom_elements(), handle_tag(), and item_post().
const UPDATE_FAILED 1
Referenced by admin_page_dbsync().
const UPDATE_SUCCESS 0
DB update return values
Referenced by admin_page_dbsync().
const XCHAN_FLAGS_HIDDEN 0x0001
Referenced by dirsearch_content(), import_xchan(), suggestion_query(), syncdirs(), and zfinger_init().
const ZCURL_TIMEOUT (-1)
Communication timeout
const ZOT_REVISION 1
Referenced by api_statusnet_config(), magic_init(), and zot_build_packet().