The Red Matrix: RedMatrix\Import\Import Class Reference
RedMatrix\Import\Import Class Reference
Public Member Functions
get_credentials ()
get_itemlist ()
get_item_ident ($item)
get_item ($item_ident)
get_taxonomy ($item_ident)
get_children ($item_ident)
convert_item ($item_ident)
convert_taxonomy ($item_ident)
convert_child ($child)
store ($item, $update=false)
run ()
Protected Attributes
$itemlist = null
$src_items = null
$items = null
Private Attributes
$credentials = null
Member Function Documentation
RedMatrix\Import\Import::convert_child ($child)
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::convert_item ($item_ident)
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::convert_taxonomy ($item_ident)
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::get_children ($item_ident)
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::get_credentials ()
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::get_item ($item_ident)
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::get_item_ident ($item)
RedMatrix\Import\Import::get_itemlist ()
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::get_taxonomy ($item_ident)
Referenced by RedMatrix\Import\Import\run().
RedMatrix\Import\Import::run ()
RedMatrix\Import\Import::store ($item, $update = false)
Member Data Documentation
RedMatrix\Import\Import::$credentials = null private
Referenced by RedMatrix\Import\Import\get_credentials().
RedMatrix\Import\Import::$itemlist = null protected
Referenced by RedMatrix\Import\Import\get_itemlist().
RedMatrix\Import\Import::$items = null protected
RedMatrix\Import\Import::$src_items = null protected
The documentation for this class was generated from the following file:
include/Import/Importer.php