The Red Matrix: include/features.php File Reference
features.php File Reference
Functions
feature_enabled ($uid, $feature)
get_features ()
Function Documentation
feature_enabled ($uid, $feature)
Referenced by apw_form(), categories_widget(), connedit_content(), conversation(), editblock_content(), editlayout_content(), editpost_content(), editwebpage_content(), Item\get_comment_box(), Item\get_template_data(), item_post(), mail_content(), mail_post(), nav(), profile_sidebar(), profiles_content(), redbasic_form(), rpost_content(), search(), searchbox(), sources_content(), sources_post(), thing_content(), widget_affinity(), widget_archive(), widget_notes(), widget_savedsearch(), widget_settings_menu(), widget_suggestions(), and widget_tagcloud_wall().
get_features ()