The Red Matrix: include/fixd.php File Reference
fixd.php File Reference
Variables
$rand = db_getfunc('RAND')
$r = q("select xchan_addr, hubloc_url from xchan left join hubloc on hubloc_hash = xchan_hash where xchan_network like '%%diaspora%%' order by $rand")
$total = 0
foreach($r as $rr) print $total n
Variable Documentation
$r = q("select xchan_addr, hubloc_url from xchan left join hubloc on hubloc_hash = xchan_hash where xchan_network like '%%diaspora%%' order by $rand")
Referenced by abook_connections(), abook_self(), abook_toggle_flag(), account_remove(), account_service_class_allows(), account_service_class_fetch(), account_total(), account_verify_password(), achievements_content(), acl_init(), add_source_route(), admin_content(), admin_page_dbsync(), admin_page_hubloc_post(), admin_page_profs(), admin_page_profs_post(), admin_page_summary(), all_friends(), allowed_public_recips(), api_call(), api_direct_messages_box(), api_direct_messages_new(), api_favorites(), api_ff_ids(), api_format_items(), api_get_user(), api_group(), api_group_members(), api_login(), api_oauth_access_token(), api_oauth_request_token(), api_red_xchan(), api_statuses_destroy(), api_statuses_f(), api_statuses_home_timeline(), api_statuses_mentions(), api_statuses_public_timeline(), api_statuses_repeat(), api_statuses_show(), api_statuses_user_timeline(), app_destroy(), app_installed(), app_list(), app_store(), app_update(), appman_content(), attach_by_hash(), attach_by_hash_nodata(), attach_change_permissions(), attach_count_files(), attach_delete(), attach_init(), attach_list_files(), attach_mkdir(), attach_store(), authenticate_success(), autoname(), bb2diaspora_itemwallwall(), bb2dmention_callback(), bb_translate_video(), block_content(), blocks_content(), bookmark_add(), build_sync_packet(), catblock(), categories_widget(), change_channel(), channel_content(), channel_remove(), channel_total(), channelx_by_hash(), channelx_by_n(), channelx_by_nick(), chanview_content(), chat_content(), chat_message(), chatroom_create(), chatroom_destroy(), chatroom_enter(), chatroom_leave(), chatroom_list(), chatroom_list_count(), chatsvc_content(), chatsvc_post(), check_account_email(), check_account_invite(), check_config(), check_item_source(), check_webbie(), collect_recipients(), comanche_block(), common_content(), common_friends(), common_friends_visitor_widget(), common_friends_zcid(), connect_init(), connect_post(), connections_content(), connections_post(), connedit_init(), connedit_post(), construct_activity_object(), construct_activity_target(), consume_feed(), contact_block(), contact_profile_assign(), contact_remove(), contact_select(), contactgroup_content(), count_all_friends(), count_common_friends(), count_common_friends_zcid(), create_account(), create_identity(), RedMatrix\RedDAV\RedDirectory\createDirectory(), RedMatrix\RedDAV\RedDirectory\createFile(), current_theme(), delegate_content(), delete_imported_item(), delete_item_lowlevel(), deliver_run(), diaspora_asphoto(), diaspora_comment(), diaspora_conversation(), diaspora_dispatch_public(), diaspora_get_contact_by_handle(), diaspora_handle_from_contact(), diaspora_like(), diaspora_mention_callback(), diaspora_message(), diaspora_photo(), diaspora_post(), diaspora_process_outbound(), diaspora_profile(), diaspora_request(), diaspora_reshare(), diaspora_retraction(), diaspora_send_images(), diaspora_send_mail(), diaspora_signed_retraction(), dir_tagadelic(), dir_tagblock(), directory_content(), dirsearch_content(), discover_by_url(), discover_by_webbie(), display_content(), downgrade_accounts(), drop_item(), editblock_content(), editlayout_content(), editwebpage_content(), encode_item(), event_addtocal(), event_store_event(), event_store_item(), events_content(), expand_groups(), expire_run(), externals_run(), fbrowser_content(), feed_init(), fileas_widget(), filer_content(), filerm_content(), filestorage_content(), filter_insecure(), find_diaspora_person_by_handle(), find_filename_by_hash(), find_folder_hash_by_attach_hash(), RedMatrix\RedDAV\RedBrowser\findAttachHash(), RedMatrix\RedDAV\RedBrowser\findAttachIdByHash(), first_post_date(), fix_attached_photo_permissions(), fix_private_photos(), fix_system_urls(), fsuggest_content(), fsuggest_post(), RedMatrix\RedDAV\RedBrowser\generateDirectoryIndex(), Cache\get(), RedMatrix\RedDAV\RedFile\get(), get_all_perms(), get_birthdays(), get_channel_by_nick(), get_channel_default_perms(), get_cloudpath(), get_diaspora_key(), get_events(), get_item_elements(), get_online_status(), get_plugin_info(), get_sys_channel(), get_theme_info(), get_things(), get_words(), RedMatrix\RedDAV\RedDirectory\getDir(), RedMatrix\RedDAV\RedDirectory\getLastModified(), gprobe_run(), group_add(), group_add_member(), group_byname(), group_content(), group_get_members(), group_post(), group_rec_byhash(), group_rmv(), group_rmv_member(), group_select(), group_side(), groups_containing(), handle_tag(), hcard_init(), home_content(), hubloc_change_primary(), identity_basic_export(), identity_check_service_class(), identity_selector(), import_author_diaspora(), import_author_rss(), import_author_unknown(), import_author_zot(), import_channel_photo(), import_directory_keywords(), import_directory_profile(), import_post(), import_profile_photo(), import_site(), import_xchan(), importelm_post(), install_plugin(), invite_post(), is_matrix_url(), is_sys_channel(), item_add_cid(), item_check_service_class(), item_expire(), item_getfeedattach(), item_message_id(), item_post(), item_remove_cid(), item_store(), item_store_update(), items_fetch(), layout_select(), layouts_content(), like_content(), list_public_sites(), load_config(), load_contact_links(), load_database(), load_hooks(), load_pconfig(), load_xconfig(), local_dir_update(), lockview_content(), locs_content(), locs_post(), FKOAuth1\loginUser(), FKOAuthDataStore\lookup_consumer(), FKOAuthDataStore\lookup_nonce(), FKOAuthDataStore\lookup_token(), lostpass_content(), lostpass_post(), magic_init(), mail_content(), mail_store(), manage_content(), mark_orphan_hubsxchans(), match_content(), match_openid(), member_of(), menu_add_item(), menu_content(), menu_create(), menu_del_item(), menu_delete(), menu_delete_id(), menu_edit(), menu_edit_item(), menu_fetch(), menu_fetch_id(), menu_list(), menu_list_count(), menu_post(), message_content(), mimetype_select(), mini_group_select(), mitem_content(), mitem_post(), mood_init(), msearch_post(), netgrowth_content(), network_content(), FKOAuthDataStore\new_access_token(), new_contact(), FKOAuthDataStore\new_request_token(), notification(), notifications_content(), notifications_off(), notifications_post(), notifier_run(), notify_content(), notify_init(), oauth_get_client(), onedirsync_run(), onepoll_run(), openid_content(), p_init(), page_content(), page_init(), pagelist_widget(), pdl_selector(), pemtome(), perm_is_allowed(), photo_init(), photo_new_resource(), photo_upload(), photos_album_exists(), photos_album_get_db_idstr(), photos_content(), photos_list_photos(), photos_post(), ping_init(), plugin_is_installed(), poco(), poco_load(), poke_content(), poke_init(), poller_run(), post_activity_item(), post_post(), preg_heart(), prep_content(), prep_init(), private_messages_drop(), private_messages_fetch_conversation(), private_messages_fetch_message(), private_messages_list(), process_channel_sync_delivery(), process_delivery(), process_location_delivery(), process_mail_delivery(), process_profile_delivery(), process_rating_delivery(), profile_init(), profile_load(), profile_photo_post(), profile_photo_set_profile_perms(), profile_sidebar(), profiles_content(), profiles_init(), profiles_post(), profperm_content(), prune_hub_reinstalls(), public_recips(), pubrsatome(), pubsub_init(), pubsub_post(), pubsubhubbub_init(), RedMatrix\RedDAV\RedFile\put(), dba_mysql\q(), dba_mysqli\q(), dba_postgres\q(), queue_run(), random_profile(), rconnect_url(), receive_post(), RedChannelList(), RedCollectionData(), RedFileData(), ref_session_read(), ref_session_write(), refimport_content(), reflect_comment_store(), register_content(), register_hook(), register_post(), relative_date(), reload_plugins(), remote_online_status(), remove_all_xchan_resources(), remove_community_tag(), remove_obsolete_hublocs(), replace_macros(), FriendicaSmartyEngine\replace_macros(), retain_item(), rmagic_init(), rmagic_post(), rpost_content(), photo_driver\save(), search_ac_init(), search_content(), send_message(), send_reg_approval_email(), send_status_notifications(), service_class_allows(), service_class_fetch(), Cache\set(), set_default_login_identity(), RedMatrix\RedDAV\RedBasicAuth\setAuthenticated(), RedMatrix\RedDAV\RedFile\setName(), RedMatrix\RedDAV\RedDirectory\setName(), settings_post(), setup_content(), share_init(), sharedwithme_content(), siteinfo_content(), siteinfo_init(), sitelist_init(), sources_content(), sources_post(), starred_init(), start_delivery_chain(), photo_driver\store(), store_diaspora_comment_sig(), store_item_tag(), stream_perms_api_uids(), stream_perms_xchans(), subthread_content(), suggest_content(), suggestion_query(), sync_directories(), sync_locations(), tag_deliver(), tagadelic(), tagblock(), tagger_content(), tagrm_content(), tagrm_post(), tgroup_check(), theme_attachments(), thing_content(), thing_init(), unregister_hook(), update_birthdays(), update_channels_active_halfyear_stat(), update_channels_active_monthly_stat(), update_channels_total_stat(), update_directory_entry(), update_remote_id(), update_suggestions(), user_allow(), user_approve(), user_deny(), RedMatrix\RedDAV\RedBasicAuth\validateUserPass(), vcard_from_xchan(), verify_email_address(), viewconnections_content(), viewsrc_content(), vote_content(), vote_init(), vote_post(), wall_attach_post(), webpages_content(), wfinger_init(), widget_bookmarkedchats(), widget_chatroom_list(), widget_filer(), widget_follow(), widget_item(), widget_random_block(), widget_savedsearch(), widget_suggestedchats(), widget_suggestions(), widget_tagcloud(), wtagblock(), xchan_content(), xchan_fetch(), xchan_store(), xrd_init(), z_input_filter(), z_readdir(), zfinger_init(), zid_init(), zot_feed(), zot_finger(), zot_gethub(), zot_import(), zot_process_message_request(), zot_process_response(), zot_refresh(), zotfeed_init(), and zping_content().
$rand = db_getfunc('RAND')
Referenced by common_friends(), list_public_sites(), and sitelist_init().
$total = 0
Referenced by admin_page_channels(), admin_page_users(), connections_content(), contact_block(), count_descendants(), Item\count_descendants(), Item\count_unseen_descendants(), externals_run(), get_birthdays(), get_events(), invite_post(), msearch_post(), onepoll_run(), and poco_load().
foreach ($r as $rr) print $total n