The Red Matrix: include/html2bbcode.php File Reference
html2bbcode.php File Reference
Functions
node2bbcode (&$doc, $oldnode, $attributes, $startbb, $endbb)
node2bbcodesub (&$doc, $oldnode, $attributes, $startbb, $endbb)
deletenode (&$doc, $node)
html2bbcode ($message)
Function Documentation
deletenode (& $doc, $node)
Referenced by html2bbcode(), and parseurl_getsiteinfo().
html2bbcode ($message)
Referenced by api_statuses_mediap(), api_statuses_update(), diaspora2bb(), and get_atom_elements().
node2bbcode (& $doc, $oldnode, $attributes, $startbb, $endbb)
Referenced by html2bbcode(), and html2plain().
node2bbcodesub (& $doc, $oldnode, $attributes, $startbb, $endbb)
Referenced by node2bbcode().