The Red Matrix: include/api.php File Reference
api.php File Reference
Functions
api_user ()
api_date ($str)
api_register_func ($path, $func, $auth=false)
api_login (&$a)
api_call (&$a)
api_rss_extra (&$a, $arr, $user_info)
api_get_user (&$a, $contact_id=Null)
api_item_get_user (&$a, $item)
api_apply_template ($templatename, $type, $data)
api_account_verify_credentials (&$a, $type)
api_account_logout (&$a, $type)
requestdata ($k)
api_export_basic (&$a, $type)
api_statuses_mediap (&$a, $type)
api_statuses_update (&$a, $type)
api_status_show (&$a, $type)
api_users_show (&$a, $type)
api_statuses_home_timeline (&$a, $type)
api_statuses_public_timeline (&$a, $type)
api_statuses_show (&$a, $type)
api_statuses_repeat (&$a, $type)
api_statuses_destroy (&$a, $type)
api_statuses_mentions (&$a, $type)
api_statuses_user_timeline (&$a, $type)
api_favorites (&$a, $type)
api_format_as ($a, $ret, $user_info)
api_format_messages ($item, $recipient, $sender)
api_format_items ($r, $user_info)
api_account_rate_limit_status (&$a, $type)
api_help_test (&$a, $type)
api_statuses_f (&$a, $type, $qtype)
api_statuses_friends (&$a, $type)
api_statuses_followers (&$a, $type)
api_statusnet_config (&$a, $type)
api_statusnet_version (&$a, $type)
api_friendica_version (&$a, $type)
api_ff_ids (&$a, $type, $qtype)
api_friends_ids (&$a, $type)
api_followers_ids (&$a, $type)
api_direct_messages_new (&$a, $type)
api_direct_messages_box (&$a, $type, $box)
api_direct_messages_sentbox (&$a, $type)
api_direct_messages_inbox (&$a, $type)
api_direct_messages_all (&$a, $type)
api_direct_messages_conversation (&$a, $type)
api_oauth_request_token (&$a, $type)
api_oauth_access_token (&$a, $type)
Variables
$API = array()
$called_api = Null
Function Documentation
api_account_logout (& $a, $type)
api_account_rate_limit_status (& $a, $type)
api_account_verify_credentials (& $a, $type)
Returns an HTTP 200 OK response code and a representation of the requesting user if authentication was successful; returns a 401 status code and an error message if not. http://developer.twitter.com/doc/get/account/verify_credentials
api_apply_template ($templatename, $type, $data)
load api $templatename for $type and replace $data array
Referenced by api_account_logout(), api_account_rate_limit_status(), api_account_verify_credentials(), api_direct_messages_box(), api_direct_messages_new(), api_favorites(), api_help_test(), api_status_show(), api_statuses_destroy(), api_statuses_followers(), api_statuses_friends(), api_statuses_home_timeline(), api_statuses_mentions(), api_statuses_public_timeline(), api_statuses_repeat(), api_statuses_show(), api_statuses_user_timeline(), api_statusnet_config(), and api_users_show().
api_call (& $a)
Referenced by api_content().
api_date ($str)
Referenced by api_format_items(), api_format_messages(), api_get_user(), api_rss_extra(), api_status_show(), and api_users_show().
api_direct_messages_all (& $a, $type)
api_direct_messages_box (& $a, $type, $box)
Referenced by api_direct_messages_all(), api_direct_messages_conversation(), api_direct_messages_inbox(), and api_direct_messages_sentbox().
api_direct_messages_conversation (& $a, $type)
api_direct_messages_inbox (& $a, $type)
api_direct_messages_new (& $a, $type)
api_direct_messages_sentbox (& $a, $type)
api_export_basic (& $a, $type)
api_favorites (& $a, $type)
api_ff_ids (& $a, $type, $qtype)
Referenced by api_followers_ids(), and api_friends_ids().
api_followers_ids (& $a, $type)
api_format_as ($a, $ret, $user_info)
Referenced by api_statuses_home_timeline(), api_statuses_mentions(), and api_statuses_public_timeline().
api_format_items ($r, $user_info)
Referenced by api_favorites(), api_statuses_home_timeline(), api_statuses_mentions(), api_statuses_public_timeline(), api_statuses_show(), and api_statuses_user_timeline().
api_format_messages ($item, $recipient, $sender)
Referenced by api_direct_messages_box(), and api_direct_messages_new().
api_friendica_version (& $a, $type)
api_friends_ids (& $a, $type)
api_get_user (& $a, $contact_id = Null)
Returns user info array.
Referenced by api_account_verify_credentials(), api_direct_messages_box(), api_direct_messages_new(), api_favorites(), api_item_get_user(), api_rss_extra(), api_status_show(), api_statuses_destroy(), api_statuses_f(), api_statuses_home_timeline(), api_statuses_mediap(), api_statuses_mentions(), api_statuses_public_timeline(), api_statuses_repeat(), api_statuses_show(), api_statuses_update(), api_statuses_user_timeline(), api_users_show(), and wall_upload_post().
api_help_test (& $a, $type)
api_item_get_user (& $a, $item)
Referenced by api_format_items().
api_login (& $a)
Simple HTTP Login
Referenced by api_call(), and api_get_user().
api_oauth_access_token (& $a, $type)
api_oauth_request_token (& $a, $type)
api_register_func ($path, $func, $auth = false)
api_rss_extra (& $a, $arr, $user_info)
RSS extra info
Referenced by api_direct_messages_box(), api_direct_messages_new(), api_favorites(), api_statuses_home_timeline(), api_statuses_mentions(), api_statuses_public_timeline(), and api_statuses_user_timeline().
api_status_show (& $a, $type)
Referenced by api_statuses_mediap(), and api_statuses_update().
api_statuses_destroy (& $a, $type)
api_statuses_f (& $a, $type, $qtype)
https://dev.twitter.com/docs/api/1/get/statuses/friends This function is deprecated by Twitter returns: json, xml
Referenced by api_statuses_followers(), and api_statuses_friends().
api_statuses_followers (& $a, $type)
api_statuses_friends (& $a, $type)
api_statuses_home_timeline (& $a, $type)
http://developer.twitter.com/doc/get/statuses/home_timeline
TODO: Optional parameters TODO: Add reply info
api_statuses_mediap (& $a, $type)
api_statuses_mentions (& $a, $type)
http://developer.twitter.com/doc/get/statuses/mentions
api_statuses_public_timeline (& $a, $type)
api_statuses_repeat (& $a, $type)
api_statuses_show (& $a, $type)
api_statuses_update (& $a, $type)
api_statuses_user_timeline (& $a, $type)
api_statusnet_config (& $a, $type)
api_statusnet_version (& $a, $type)
api_user ()
Referenced by api_account_verify_credentials(), api_call(), api_direct_messages_box(), api_direct_messages_new(), api_export_basic(), api_favorites(), api_ff_ids(), api_get_user(), api_statuses_destroy(), api_statuses_f(), api_statuses_home_timeline(), api_statuses_mediap(), api_statuses_mentions(), api_statuses_public_timeline(), api_statuses_repeat(), api_statuses_show(), api_statuses_update(), and api_statuses_user_timeline().
api_users_show (& $a, $type)
Returns extended information of a given user, specified by ID or screen name as per the required id parameter. The author's most recent status will be returned inline. http://developer.twitter.com/doc/get/users/show
requestdata ($k)
get data from $_REQUEST (e.g. $_POST or $_GET)
Referenced by api_statuses_mediap(), and api_statuses_update().
Variable Documentation
$API = array()
TWITTER API
Referenced by api_call(), and api_register_func().
$called_api = Null
Referenced by api_call(), and api_get_user().