The Red Matrix: include/plugin.php File Reference
plugin.php File Reference
Functions
unload_plugin ($plugin)
uninstall_plugin ($plugin)
install_plugin ($plugin)
load_plugin ($plugin)
reload_plugins ()
register_hook ($hook, $file, $function, $priority=0)
unregister_hook ($hook, $file, $function)
load_hooks ()
call_hooks ($name, &$data=null)
get_plugin_info ($plugin)
get_theme_info ($theme)
get_theme_screenshot ($theme)
service_class_allows ($uid, $property, $usage=false)
service_class_fetch ($uid, $property)
upgrade_link ($bbcode=false)
upgrade_message ($bbcode=false)
upgrade_bool_message ($bbcode=false)
head_add_css ($src, $media= 'screen')
head_get_css ()
format_css_if_exists ($source)
head_add_js ($src)
head_get_js ()
format_js_if_exists ($source)
theme_include ($file, $root= '')
get_intltext_template ($s, $root= '')
get_markup_template ($s, $root= '')
Function Documentation
call_hooks ($name, & $data = null)
Referenced by api_login(), atom_author(), atom_entry(), authenticate_success(), avatar_img(), bb2diaspora(), bbcode(), channel_remove(), check_account_email(), check_account_invite(), check_account_password(), connect_content(), connections_content(), connections_post(), contact_block(), contact_select(), conversation(), create_identity(), cronhooks_run(), directory_content(), editblock_content(), editlayout_content(), editpost_content(), editwebpage_content(), event_store(), feature_enabled(), gender_selector(), get_all_perms(), get_atom_elements(), get_features(), get_feed_for(), get_mood_verbs(), get_perms(), get_poke_verbs(), Item\get_template_data(), App\get_widgets(), group_select(), html2bbcode(), import_directory_profile(), item_photo_menu(), item_post(), item_store(), item_store_update(), like_content(), login(), FKOAuth1\loginUser(), magic_init(), mail_store(), marital_selector(), mood_init(), nav(), network_content(), network_to_name(), new_contact(), notification(), notifier_run(), obj_verbs(), oembed_fetch_url(), parse_url_content(), pdl_selector(), perm_is_allowed(), photo_upload(), photos_content(), ping_init(), post_activity_item(), post_init(), prepare_body(), proc_run(), profile_content(), profile_sidebar(), profile_tabs(), profiles_content(), profiles_post(), settings_post(), sexpref_selector(), siteinfo_content(), smilies(), subthread_content(), validate_channelname(), wfinger_init(), xrd_init(), zid(), and zid_init().
format_css_if_exists ($source)
Referenced by head_get_css().
format_js_if_exists ($source)
Referenced by head_get_js().
get_intltext_template ($s, $root = '')
Referenced by check_config(), lostpass_content(), lostpass_post(), send_reg_approval_email(), send_verification_email(), setup_post(), and user_allow().
get_markup_template ($s, $root = '')
Referenced by admin_content(), admin_page_dbsync(), admin_page_logs(), admin_page_plugins(), admin_page_site(), admin_page_summary(), admin_page_themes(), admin_page_users(), advanced_profile(), allfriends_content(), alt_pager(), api_apply_template(), api_content(), apps_content(), blocks_content(), App\build_pagehead(), categories_widget(), channel_content(), chanview_content(), check_php(), common_content(), common_friends_visitor_widget(), connect_content(), connections_content(), construct_page(), contact_block(), conversation(), crepair_content(), delegate_content(), directory_content(), dirfind_content(), display_content(), editblock_content(), editlayout_content(), editpost_content(), editwebpage_content(), events_content(), fbrowser_content(), field_timezone(), fileas_widget(), filer_content(), findpeople_widget(), follow_widget(), get_birthdays(), Item\get_comment_box(), get_events(), get_feed_for(), group_content(), group_side(), help_content(), hostxrd_init(), import_content(), intro_content(), invite_content(), lang_selector(), lastpost_content(), layouts_content(), login(), lostpass_content(), manage_content(), match_content(), menu_content(), menu_render(), message_aside(), message_content(), micropro(), mini_group_select(), mitem_content(), mood_content(), nav(), network_content(), new_channel_content(), nogroup_content(), notification(), notifications_content(), notify_content(), oembed_format_object(), oexchange_init(), opensearch_init(), pagelist_widget(), photos_album_widget(), photos_content(), poco_init(), poke_content(), populate_acl(), posted_date_widget(), profile_sidebar(), profile_tabs(), profiles_content(), redbasic_form(), register_content(), removeme_content(), rmagic_content(), saved_searches(), search_content(), settings_aside(), setup_content(), siteinfo_content(), suggest_content(), thing_content(), vcard_from_xchan(), viewconnections_content(), vote_content(), webpages_content(), writepages_widget(), and xrd_init().
get_plugin_info ($plugin)
Referenced by admin_page_plugins().
get_theme_info ($theme)
Referenced by admin_page_themes(), and pretheme_init().
get_theme_screenshot ($theme)
Referenced by admin_page_themes(), and pretheme_init().
head_add_css ($src, $media = 'screen')
Referenced by construct_page(), and redstrap_init().
head_add_js ($src)
Referenced by construct_page(), and redstrap_init().
head_get_css ()
Referenced by App\build_pagehead().
head_get_js ()
Referenced by App\build_pagehead().
install_plugin ($plugin)
Referenced by admin_page_plugins().
load_hooks ()
Referenced by check_config(), and cli_startup().
load_plugin ($plugin)
Referenced by check_config(), and install_plugin().
register_hook ($hook, $file, $function, $priority = 0)
reload_plugins ()
Referenced by poller_run().
service_class_allows ($uid, $property, $usage = false)
Referenced by identity_check_service_class(), and new_contact().
service_class_fetch ($uid, $property)
Referenced by attach_store(), photo_upload(), and photos_content().
theme_include ($file, $root = '')
Referenced by construct_page(), format_css_if_exists(), format_js_if_exists(), FriendicaSmartyEngine\get_intltext_template(), FriendicaSmartyEngine\get_markup_template(), Template\get_markup_template(), and App\set_widget().
uninstall_plugin ($plugin)
Referenced by admin_page_plugins().
unload_plugin ($plugin)
Referenced by check_config(), and uninstall_plugin().
unregister_hook ($hook, $file, $function)
upgrade_bool_message ($bbcode = false)
upgrade_link ($bbcode = false)
Referenced by upgrade_bool_message(), and upgrade_message().
upgrade_message ($bbcode = false)
Referenced by attach_store(), identity_check_service_class(), new_contact(), and photo_upload().