The Red Matrix: view/theme/redbasic/php/style.php File Reference
style.php File Reference
Variables
$uid = get_theme_uid()
if ($uid) load_pconfig($uid
$line_height = false
$redbasic_font_size = false
$resolution = false
$colour = false
$shadows = false
$navcolour = false
$nav_bg_1 = "f88"
$nav_bg_2 = "b00"
$nav_bg_3 = "f00"
$nav_bg_4 = "b00"
$displaystyle = false
$linkcolour = false
$shiny = false
$radius = 5
$site_line_height = get_config("redbasic","line_height")
$site_redbasic_font_size = get_config("redbasic", "font_size")
$site_colour = get_config("redbasic", "colour")
$x = get_config('redbasic','radius')
Variable Documentation
$colour = false
Referenced by redbasic_form(), and theme_content().
$displaystyle = false
Referenced by redbasic_form(), and theme_content().
$line_height = false
Referenced by redbasic_form(), and theme_content().
$linkcolour = false
Referenced by redbasic_form(), and theme_content().
$nav_bg_1 = "f88"
$nav_bg_2 = "b00"
$nav_bg_3 = "f00"
$nav_bg_4 = "b00"
$navcolour = false
Referenced by redbasic_form(), and theme_content().
$radius = 5
Referenced by redbasic_form(), and theme_content().
$redbasic_font_size = false
$resolution = false
Referenced by photo_init().
$shadows = false
Referenced by redbasic_form().
$shiny = false
Referenced by redbasic_form(), and theme_content().
$site_colour = get_config("redbasic", "colour")
$site_line_height = get_config("redbasic","line_height")
$site_redbasic_font_size = get_config("redbasic", "font_size")
$uid = get_theme_uid()
Referenced by admin_page_users(), admin_page_users_post(), all_friends(), build_sync_packet(), check_list_permissions(), common_friends(), common_friends_zcid(), contacts_not_grouped(), count_all_friends(), count_common_friends(), count_common_friends_zcid(), current_theme_url(), del_pconfig(), delete_imported_item(), drop_items(), events_post(), feature_enabled(), first_post_date(), fix_attached_photo_permissions(), fix_private_photos(), follow_init(), follow_widget(), get_all_perms(), get_pconfig(), get_theme_uid(), group_add(), group_add_member(), group_byname(), group_rec_byhash(), group_rmv(), group_rmv_member(), groups_containing(), import_channel_photo(), item_expire(), item_post(), item_store_update(), items_fetch(), load_contact_links(), load_pconfig(), FKOAuth1\loginUser(), menu_add_item(), menu_del_item(), menu_delete(), menu_delete_id(), menu_edit_item(), menu_fetch(), mini_group_select(), mood_init(), new_contact(), notifier_run(), pdl_selector(), perm_is_allowed(), photo_init(), poke_init(), posted_date_widget(), posted_dates(), private_messages_list(), remove_community_tag(), send_message(), service_class_allows(), service_class_fetch(), set_pconfig(), Conversation\set_profile_owner(), photo_driver\store(), store_item_tag(), suggestion_query(), syncdirs(), tag_deliver(), tagadelic(), tagblock(), tgroup_check(), and zot_feed().
$x = get_config('redbasic','radius')
Referenced by Template\_replcb_for(), Template\_replcb_if(), account_remove(), acl_init(), activity_sanitise(), admin_page_themes(), aes_encapsulate(), argv(), array_sanitise(), attach_store(), autoname(), blocks_content(), build_sync_packet(), change_channel(), channel_content(), check_config(), check_form_security_token(), check_list_permissions(), check_webbie(), common_init(), construct_page(), conversation(), crepair_post(), photo_gd\cropImage(), photo_imagick\cropImage(), datesel(), datesel_format(), decode_tags(), deliver_run(), dir_tagadelic(), directory_content(), directory_run(), display_content(), email_header_encode(), encode_item(), encode_mail(), event_store(), expand_groups(), feature_enabled(), fetch_post_tags(), find_xchan_in_array(), findpeople_widget(), fix_private_photos(), fix_system_urls(), photo_gd\flip(), fsuggest_post(), generate_user_guid(), get_all_perms(), get_item_elements(), get_mail_elements(), get_mentions(), get_profile_elements(), get_terms_oftype(), gprobe_run(), ids_to_querystr(), import_author_xchan(), import_directory_keywords(), import_directory_profile(), import_post(), import_xchan(), invite_content(), invite_post(), item_post(), json_decode_plus(), json_return_and_die(), lastpost_content(), layouts_content(), legal_webbie(), lrdd(), magic_init(), manage_content(), match_content(), menu_content(), menu_delete_id(), menu_fetch(), menu_render(), message_post(), mimetype_select(), navbar_complete(), network_content(), network_init(), new_channel_init(), new_contact(), notification(), notifier_run(), oembed_fetch_url(), onepoll_run(), parse_xml_string(), perm_is_allowed(), photos_post(), ping_init(), poco_load(), poller_run(), post_init(), post_post(), preg_heart(), prepare_body(), print_template(), private_messages_list(), proc_run(), process_mail_delivery(), profile_init(), profile_load(), profile_photo_post(), public_recips(), dba_mysql\q(), dba_mysqli\q(), randprof_init(), remove_community_tag(), photo_driver\save(), search_ac_init(), send_status_notifications(), App\set_widget(), site_default_perms(), smilies(), photo_driver\store(), stringify_array_elms(), sync_directories(), tag_deliver(), tagadelic(), tagrm_content(), tagrm_post(), theme_status(), timesel(), toggle_theme(), update_imported_item(), upgrade_bool_message(), upgrade_message(), valid_email(), webpages_content(), xchan_query(), xmlify(), zfinger_init(), zot_process_response(), zot_refresh(), and zot_register_hub().
if ($colour==="dark") if (($redbasic_font_size >=8.0)&&($redbasic_font_size<=20.0)) if (($line_height >=1.0)&&($line_height<=2.0)) if($shadows==="true")