{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Caro/a {{$username}},

	'{{$from}}' ha commentato un elemeto/conversazione che stai seguendo.

-----
{{$body}}
-----

Accedi a {{$siteurl}} per verdere la conversazione completa:

{{$display}}

Grazie,
	L'amministratore di {{$sitename}}

 

