{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Ciao {{$myname}},

Un nuovo utente ha iniziato a seguirti su {{$sitename}} - '{{$requestor}}'.

Puoi vedere il suo profilo su {{$url}}.

Accedi sul tuo sito per approvare o ignorare la richiesta.

{{$siteurl}}

Saluti,

	L'amministratore di {{$sitename}}