{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Ciao {{$username}},
	Su {{$sitename}} è stata ricevuta una richiesta di azzeramento di password per un account. 
Per confermare la richiesta, clicca sul link di verifica
qui in fondo oppure copialo nella barra degli indirizzi del tuo browser. 

Se NON hai richiesto l'azzeramento, NON seguire il link
e ignora e/o cancella questa email. 

La tua password non sarà modificata finché non avremo verificato che
hai fatto questa richiesta. 

Per verificare la tua identità clicca su:

{{$reset_link}}

Dopo la verifica riceverai un messaggio di risposta con la nuova password.

Potrai cambiare la password dalla pagina delle impostazioni dopo aver effettuato l'accesso.

I dati di accesso sono i seguenti:

Sito:»{{$siteurl}}
Nome utente:»{{$email}}




Saluti,
	l'amministratore di {{$sitename}}

 