{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
Hai ricevuto un nuovo messsaggio privato su {{$siteName}} da '{{$from}}'.
	
{{$title}}

{{$textversion}}
				
Accedi a {{$siteurl}} per leggere e rispondere ai tuoi messaggi privati.

Grazie,
L'amministratore di {{$siteName}}
