{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Su {{$sitename}} è stata ricevuta una nuova richiesta di registrazione da parte di un utente che richiede 
la tua approvazione. 


I tuoi dati di accesso sono i seguenti:

Nome completo:»{{$username}}
Sito:»{{$siteurl}}
Nome utente:»{{$email}}


Per approvare questa richiesta clicca su:


{{$siteurl}}/regmod/allow/{{$hash}} 


Per negare la richiesta e rimuove il profilo, clicca su:


{{$siteurl}}/regmod/deny/{{$hash}}


Grazie.
