{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Caro {{$username}},

	'{{$from}}' ha scritto sulla tua bacheca.

-----
{{$body}}
-----

Vai su {{$siteurl}} per vedere o cancellare il post:

{{$display}}

Grazie,
	L'amministratore di {{$sitename}}

 

