{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}

Caro/a {{$username}},

	'{{$from}}' ha scritto qualcosa sulla bachecha del tuo profilo.

-----
{{$body}}
-----

Accedi a  {{$siteurl}} per vedere o cancellare l'elemento:

{{$display}}

Grazie,
	L'amministratore di {{$sitename}}

 

