<XML>
  <post>
    <status_message>
      <raw_message>$body</raw_message>
      <guid>$guid</guid>
      <diaspora_handle>$handle</diaspora_handle>
      <public>$public</public>
      <created_at>$created</created_at>
    </status_message>
  </post>
</XML>